#!/usr/bin/env python3
"""
Metal Gear Solid 1, 2 & 3 (Master Collection) — Steam Deck & SteamOS Mod Kit
============================================================================
A guided, dependency-free installer for the "essential" vanilla-faithful mod
stack on the Steam Deck, Steam Machine, and any SteamOS / Linux Steam install.

It will:
  1. Auto-detect your MGS1 / MGS2 / MGS3 Master Collection installs
     (incl. microSD and secondary libraries).
  2. MGS2/MGS3: install MGSHDFix (resolution / 16:10 / FOV / CPU fixes).
  3. MGS2/MGS3: install the Community Bugfix Compilation (Base) — restores the
     original PS2 textures/models and fixes the port's broken assets.
  4. MGS2/MGS3: optionally install the Better Audio Mod from a zip you supply
     (it lives on NexusMods, which requires a login, so it cannot be fetched
     automatically).
  5. MGS2/MGS3: write a KNOWN-GOOD MGSHDFix.settings file.
  6. MGS2/MGS3: set the Konami launcher's own options — including "high
     quality cinematics" — so the launcher can be skipped entirely.
  7. MGS1: install MGSM2Fix (M2-emulator fix: analog deadzone removal,
     censored-texture restorations, skippable notices, custom resolution).

Steps 5 and 6 are the whole reason this kit exists. MGSHDFix has no runtime defaults:
without a complete settings file it refuses to boot, and it hard-aborts on any
single missing section or key. That file can only be produced by its Windows
Config Tool, and its ini section names are NOT the names shown in that tool's
UI, so hand-writing one does not work. This kit ships a canonical file captured
from the real Config Tool, so you never have to run it under Proton.

Mods are downloaded live from their official GitHub releases — nothing is
rehosted here. Every auto-downloaded archive is checked against a pinned
SHA-256 before it is touched (see *_SHA256 below).

Installs are TRANSACTIONAL. Each archive is extracted to a staging folder and
every path is validated (no absolute paths, no `../` traversal, no symlinks)
before anything is copied into the live game directory. Overwritten originals
are backed up and every change is recorded in a manifest, so a mid-install
failure rolls back cleanly and `--uninstall` reverses the whole thing later.

It deliberately does NOT set Steam launch options: Steam rewrites its config
from memory and will silently revert edits made while it is running. The one
line you must paste is shown at the end.

Requirements (all preinstalled on SteamOS): python3, bsdtar, and kdialog OR
zenity. No pip packages, no sudo.

Run it from the Desktop (Konsole):  python3 install.py
Uninstall a previous run:           python3 install.py --uninstall
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

UA = "Mozilla/5.0 (X11; Linux x86_64) mgs-mc-deck-modkit"

MODKIT_VERSION = "1.3.0"

# Directory (inside each game folder) where this kit records what it installed,
# keeps backups of any files it overwrote, and stages archives before copying
# them into place. It is the anchor for repair/uninstall — see InstallTxn.
MODKIT_DIRNAME = "mgs-modkit"
MANIFEST_NAME = "manifest.json"

# Overwritten originals larger than this are recorded but NOT copied into the
# backup folder — backing up multi-GB game assets (the Better Audio Mod
# replaces some) would double disk usage for no real benefit, since Steam's
# "Verify integrity of game files" restores them for free. Small fix files
# (dlls, .asi, .ini, save files) are always backed up so uninstall is exact.
BACKUP_MAX_BYTES = 64 * 1024 * 1024

# ---------------------------------------------------------------------------
# Pinned versions.
#
# These three versions are pinned ON PURPOSE. The bundled MGSHDFix.settings
# below was generated by MGSHDFix 3.1.0's own Config Tool, and a future
# MGSHDFix release may rename ini sections/keys — which would make the game
# hard-abort on launch. Pinning guarantees a tested, working combination.
# To move to a newer MGSHDFix, bump HDFIX_VERSION and regenerate the settings
# file with the Config Tool (see README).
# ---------------------------------------------------------------------------
HDFIX_VERSION = "3.1.0"
HDFIX_URL = (
    "https://github.com/ShizCalev/MGSHDFix/releases/download/"
    f"{HDFIX_VERSION}/MGSHDFix_{HDFIX_VERSION}.zip"
)
# SHA-256 of the release asset above, so a tampered/truncated download is
# caught before it touches the game folder. Regenerate with `sha256sum` after
# bumping a version (see tools/refresh_checksums.py).
HDFIX_SHA256 = "ec42a40a26d80425496cf20a52c13d91f1523d74472c77183dda0aaf0d46db33"

# MGS1 (M2 emulator) fix — nuggslet's MGSM2Fix. Ships its own MGSM2Fix.ini
# whose defaults are already vanilla-faithful (censored-texture restorations
# on, analog deadzone removal, notice-skip), so we install it as-is.
M2FIX_VERSION = "3.6.0"
M2FIX_TAG = "v3.6"
M2FIX_URL = (
    "https://github.com/nuggslet/MGSM2Fix/releases/download/"
    f"{M2FIX_TAG}/MGSM2Fix_{M2FIX_VERSION}.zip"
)
M2FIX_SHA256 = "a979dea88acd8324b269b101a79293d32674af03d64e800ab9978216b215410d"

GAMES = {
    "mgs2": {
        "key": "mgs2",
        "name": "Metal Gear Solid 2: Sons of Liberty",
        "short": "MGS2",
        "appid": "2131640",
        "dirname": "MGS2",
        "exe": "METAL GEAR SOLID2.exe",
        # Region value the Config Tool writes for this title's option list.
        "region": "eu",
        "bugfix_version": "2.2.0",
        "bugfix_url": (
            "https://github.com/ShizCalev/MGS2-Community-Bugfix-Compilation/"
            "releases/download/2.2.0/"
            "MGS2-Community-Bugfix-Compilation_Base_v2.2.0.zip"
        ),
        "bugfix_sha256":
            "c09d2c51128d389af1e90a4356dbfbca1e0cd63beb8f5e1ae76200b00b42c131",
        "bugfix_asi": "MGS2-Community-Bugfix-Compilation.asi",
        "audio_page": "https://www.nexusmods.com/metalgearsolid2mc/mods/3",
    },
    "mgs3": {
        "key": "mgs3",
        "name": "Metal Gear Solid 3: Snake Eater",
        "short": "MGS3",
        "appid": "2131650",
        "dirname": "MGS3",
        "exe": "METAL GEAR SOLID3.exe",
        "region": "us",
        "bugfix_version": "1.1.0",
        "bugfix_url": (
            "https://github.com/ShizCalev/MGS3-Community-Bugfix-Compilation/"
            "releases/download/1.1.0/"
            "MGS3-Community-Bugfix-Compilation_Base_v1.1.0.zip"
        ),
        "bugfix_sha256":
            "1bc091847726560e31f019e9a327303623bf646bbb6bd0adc1d9a18cabb754f9",
        "bugfix_asi": "MGS3-Community-Bugfix-Compilation.asi",
        "audio_page": "https://www.nexusmods.com/metalgearsolid3mc/mods/4",
    },
    "mgs1": {
        "key": "mgs1",
        "kind": "m2fix",
        "name": "Metal Gear Solid (1)",
        "short": "MGS1",
        "appid": "2131630",
        "dirname": "MGS1",
        "exe": "METAL GEAR SOLID.exe",
        "launch": 'WINEDLLOVERRIDES="dinput8=n,b;d3d11=n,b" %command%',
    },
}

LAUNCH_OPTIONS = 'WINEDLLOVERRIDES="wininet,winhttp=n,b" %command%'

# What the Better Audio pages actually ship (verified July 2026). Nexus
# download filenames end in -<modid>-<major>-<minor>-<timestamp>.<ext>;
# the modid identifies the page, so update archives with generic names
# (e.g. "Update 2.0-4-2-0-....zip") can be matched without "MGS3" in the name.
#
#   MGS2 (mod 3): one archive — "Full Version" v2.0. Nothing else needed.
#   MGS3 (mod 4): TWO required archives — the ~2.7 GB main mod, which is
#                 v1.0 and NOT obsolete, plus the small "Update 2.0" patch
#                 installed after it. (An optional "HQ Ending Cutscenes"
#                 archive also exists — higher-bitrate ending audio.)
#
# All checks below are advisory warnings, never hard blocks, so a stale
# entry here can't strand anyone.
AUDIO_EXPECT = {
    "MGS2": {"modid": 3, "full": (2, 0), "update": None},
    "MGS3": {"modid": 4, "full": (1, 0), "update": (2, 0)},
}
NEXUS_SUFFIX = re.compile(r"-(\d+)-(\d+)-(\d+)-(\d{9,11})\.(?:zip|7z|rar)$",
                          re.IGNORECASE)

# ---------------------------------------------------------------------------
# Canonical MGSHDFix.settings (MGSHDFix 3.1.0).
#
# Captured verbatim from the real "MGSHDFix Config Tool.exe" — 150 lines,
# 96 keys, 27 sections. Placeholders (@NAME@) are substituted at write time.
# Written with CRLF line endings, exactly as the Config Tool writes it.
#
# Note the section names: [Internal Settings], [Launcher Config],
# [Skip Logo Screens], [MGS2 - Model Options] ... these are NOT the tab labels
# shown in the Config Tool's UI. Getting these wrong makes the game refuse to
# start with "Failed to read config key 'X' in section 'Y': Section not found".
# ---------------------------------------------------------------------------
SETTINGS_TEMPLATE = """\
[Bugfixes]
Fix  High  CPU  Usage="Full"
Fix Achievement Stat Tracking=1
Fix Aiming After Equip=1
Fix Aiming On Full Tilt=1
Fix Alt-Tab Loading Bugs=1
Fix Effect Speeds=1
Fix Mouse Cursor Showing=1
Fix Rain Width=1
Fix UI Width=1
Line Scale Size=360
MGS2 - Fix Optical Camo Refraction=1

[CAUTION - THIS WILL RESET ALL ACHIEVEMENTS]
Reset All Achievements=0
Safety Switch=0

[Camera Positioning]
Disable HD Collection Camera Positioning=0
HD Collection Camera Toggle="F6"

[Caption Settings]
Caption Opacity (%)=100
Caption Outline Opacity (%)=100
Caption Size (%)=100

[Controller Settings]
Button Icons="@BUTTON_ICONS@"
Set Menu OK && Cancel Button="Default"

[DISABLE STEAM ACHIEVEMENTS]
Disable Unlocking Steam Achievements=0

[Damaged Steam Cloud Save Data Fix]
Enable Console Notification When Fixed=1
Fix Mode="Move Outdated Save Data to Backup Folder"

[Enable Game Warnings]
Warn When FSR Upscaling is Enabled=1
Warn When Game is Muted=1
Warn When Missing Major Bugfix Mods=1
Warn When Save Files Are Read-Only=1
Warn When Save Folders Not Writable=1
Warn When Windows Slideshow Enabled=1

[Hotkeys]
Capture Hotkeys While Alt-Tabbed=0
Cycle Wireframe Mode="End"
Toggle Always Show Grass="Page Up"
Toggle Rain Shader="Insert"
Toggle UI Shader="Delete"

[Internal Resolution / Render Scale (+ Downsampling / Supersampling / 21:9+ and 4:3 Support)]
Render Height=0
Render Width=0

[Internal Settings]
Debug Logging=0

[Keep Aiming After Firing]
Always Keep Aiming=0
MGS2 - While in FPS Mode=0
While Holding Lock On=1
While in First Person=1

[Language Settings]
Game Language="en"
Game Region="@REGION@"

[Launcher Config]
MSX Skip Launcher Game="Metal Gear (MSX)"
Skip Launcher=@SKIP_LAUNCHER@

[MGS2 - Difficulty Restoration]
Enable Grenade Cooking=0
Restore PS2 Solidus Choking Difficulty="Disabled"
Toggle Grenade Cooking="Num9"

[MGS2 - First Person Shooter Mode]
Enable First Person Shooter Mode=0
First Person Shooter - Movement Enabled By Default=1
Tap to Keep First Person View Active=0
Toggle First Person Shooter Mode="Right"
Toggle First Person Shooter Movement="Down"
Toggle Tap for First Person View="Up"

[MGS2 - Model Options]
Force High Quality Hostages=1
Force High Quality Marines=1
Force High Quality Player Models=1
Force RTC Hostage Type="Normal"

[MGS2 - Third Person Freecam]
Camera - Zoom In Hotkey="WheelUp"
Camera - Zoom Out Hotkey="WheelDown"
Camera - Zoom Reset Hotkey="Mouse4"
Camera - Zoom Speed=25
Camera - Zoom Step Amount=250
Enable Third Person Freecam=0
Horizontal Camera Sensitivity=0.600000
Inherit Camera Rotation=0
Inherit Camera Rotation Toggle="NumMultiply"
Max Camera Distance=4000
Third Person View Toggle="Mouse5"
Vertical Camera Sensitivity=0.400000

[MGS3 - Override Render Distance]
Always Show Grass=1
Custom Grass Distance Multiplier=1.000000

[Mouse Sensitivity]
Override Mouse Sensitivity=0
X Multiplier=1
Y Multiplier=1

[Skip Logo Screens]
Skip In-Game Splashscreens=@SKIP_SPLASH@
Skip Launcher Splashscreens=@SKIP_SPLASH@

[System Specific Fixes]
Audio Output Mode="@AUDIO_MODE@"
Disable Windows Fullscreen Optimization=0
Limit Game to 2 CPU Cores=0

[Texture Filtering]
Anisotropic Filtering Level=16
Nearest Neighbor Texture Filtering=0

[Ultra-Wide / 16:10+]
Fix Aspect Ratio=1
Fix FOV=1
Fix Framebuffer=1
Lock HUD && Movies to 16:9=0

[Update Notifications]
Check For MGSHDFix Updates=@UPDATE_CHECK@
In-Game Update Notifications=1

[Various]
MGS2 - Force Sunglasses="Normal"
MGS2 - Restore Japanese Phone Ringtone=1
MGS2 - Restore Original Dogtag Names=1
Pause On Focus Loss=0

[Window Settings]
Enable Resolution Overrides=1
Fullscreen, Borderless, and Windowed="Borderless Fullscreen"
Window Height=0
Window Width=0

"""

SETTINGS_EXPECTED_SECTIONS = 27
SETTINGS_EXPECTED_KEYS = 96

# ---------------------------------------------------------------------------
# The Konami launcher's own settings.
#
# The launcher persists its options to
#   <game>/<name>_savedata_win/<steamid64>/launcher/launcher_sv
# which is plain JSON with a UTF-8 BOM, stored as two parallel arrays:
#   {"keyList":["HiresoMovie",...],"valueList":["1",...]}
#
# The keys we care about:
#   HiresoMovie    1 = "high quality" cinematics  (the one everyone wants)
#   HiresoRender   internal resolution   -> 0, MGSHDFix owns resolution
#   HiresoUpScale  internal upscaling    -> 0, ditto
#   HiresoTexture  high-res textures (MGS3 only)
#
# Writing this ourselves is what lets the kit skip the launcher entirely:
# otherwise the launcher is the ONLY place those options can be set.
#
# Templates below are used only when no save exists yet (a fresh install).
# When one already exists we patch it in place and leave everything else —
# volume, language, MGS2's big ScenarioSave blob — untouched.
# ---------------------------------------------------------------------------
LAUNCHER_TEMPLATES = {
    "mgs2": (
        ["GDPRHash", "firstStart", "languageLauncher", "HiresoPreset",
         "launcherMasterVolume", "launcherMute", "HiresoRender",
         "HiresoUpScale", "HiresoMovie", "prevPlayLanguage",
         "prevPlayLanguage2", "prevGameRegion", "prevSelectStartUpNumber"],
        ["first", "0", "1", "2", "10", "0", "0", "0", "1", "2", "0", "2", "-1"],
    ),
    "mgs3": (
        ["GDPRHash", "firstStart", "languageLauncher", "HiresoPreset",
         "HiresoRender", "HiresoUpScale", "HiresoMovie", "HiresoTexture",
         "launcherMasterVolume", "launcherMute", "prevPlayLanguage",
         "prevPlayLanguage2", "prevGameRegion", "prevSelectStartUpNumber"],
        ["first", "0", "1", "2", "0", "0", "1", "0", "10", "0", "2", "0",
         "1", "-1"],
    ),
}

STEAMID64_BASE = 76561197960265728


# ---------------------------------------------------------------------------
# Tiny GUI abstraction: prefer kdialog (KDE/Deck desktop), fall back to zenity,
# then to a plain-terminal prompt so the script still works headless.
# ---------------------------------------------------------------------------
class UI:
    def __init__(self) -> None:
        self.kind = (
            "kdialog" if shutil.which("kdialog")
            else "zenity" if shutil.which("zenity")
            else "term"
        )

    def _run(self, args: list[str]) -> tuple[int, str]:
        p = subprocess.run(args, capture_output=True, text=True)
        return p.returncode, p.stdout.strip()

    def info(self, text: str, title: str = "MGS Deck Mod Kit") -> None:
        if self.kind == "kdialog":
            self._run(["kdialog", "--title", title, "--msgbox", text])
        elif self.kind == "zenity":
            self._run(["zenity", "--info", "--title", title,
                       "--no-wrap", "--text", text])
        else:
            print(f"\n=== {title} ===\n{text}\n")

    def error(self, text: str, title: str = "MGS Deck Mod Kit — Error") -> None:
        if self.kind == "kdialog":
            self._run(["kdialog", "--title", title, "--error", text])
        elif self.kind == "zenity":
            self._run(["zenity", "--error", "--title", title,
                       "--no-wrap", "--text", text])
        else:
            print(f"\n!!! {title} !!!\n{text}\n", file=sys.stderr)

    def yesno(self, text: str, title: str = "MGS Deck Mod Kit") -> bool:
        if self.kind == "kdialog":
            return self._run(["kdialog", "--title", title, "--yesno", text])[0] == 0
        if self.kind == "zenity":
            return self._run(["zenity", "--question", "--title", title,
                              "--no-wrap", "--text", text])[0] == 0
        return input(f"{text} [y/N] ").strip().lower().startswith("y")

    def pick_dir(self, text: str) -> str | None:
        start = str(Path.home())
        if self.kind == "kdialog":
            rc, out = self._run(["kdialog", "--title", text,
                                 "--getexistingdirectory", start])
            return out or None if rc == 0 else None
        if self.kind == "zenity":
            rc, out = self._run(["zenity", "--file-selection", "--directory",
                                 "--title", text])
            return out or None if rc == 0 else None
        ans = input(f"{text}\nPath: ").strip()
        return ans or None

    def pick_file(self, text: str, start: Path | None = None) -> str | None:
        start_s = str(start or (Path.home() / "Downloads"))
        if self.kind == "kdialog":
            rc, out = self._run(["kdialog", "--title", text,
                                 "--getopenfilename", start_s, "*.zip *.7z *.rar"])
            return out or None if rc == 0 else None
        if self.kind == "zenity":
            rc, out = self._run(["zenity", "--file-selection", "--title", text,
                                 "--filename", start_s + "/"])
            return out or None if rc == 0 else None
        ans = input(f"{text}\nPath to archive (blank to skip): ").strip()
        return ans or None

    def checklist(self, title: str, text: str,
                  items: list[tuple[str, str, bool]]) -> list[str] | None:
        """items: (tag, label, checked).

        Returns the selected tags, or ``None`` if the user CANCELLED the
        dialog. That distinction matters: an empty list means "the user
        deliberately unchecked everything", whereas None means "the user
        backed out" — the caller keeps its defaults instead of silently
        treating a cancel as "turn every option off".
        """
        if self.kind == "kdialog":
            args = ["kdialog", "--title", title, "--separate-output",
                    "--checklist", text]
            for tag, label, chk in items:
                args += [tag, label, "on" if chk else "off"]
            rc, out = self._run(args)
            return out.splitlines() if rc == 0 else None
        if self.kind == "zenity":
            args = ["zenity", "--list", "--checklist", "--title", title,
                    "--text", text,
                    "--column", "Pick", "--column", "Tag", "--column", "Item",
                    "--hide-column", "2", "--print-column", "2"]
            for tag, label, chk in items:
                args += ["TRUE" if chk else "FALSE", tag, label]
            rc, out = self._run(args)
            if rc != 0:
                return None
            return out.split("|") if out else []
        print(f"\n{title}\n{text}")
        for i, (tag, label, chk) in enumerate(items):
            print(f"  [{i}] {'x' if chk else ' '} {label}")
        raw = input("Enter numbers to toggle (space-separated, "
                    "blank=keep defaults, 'c'=cancel): ")
        if raw.strip().lower() == "c":
            return None
        chosen = {tag for tag, _, chk in items if chk}
        if raw.strip():
            toggles = {int(x) for x in raw.split() if x.isdigit()}
            chosen = set()
            for i, (tag, _, chk) in enumerate(items):
                if chk ^ (i in toggles):
                    chosen.add(tag)
        return list(chosen)

    def menu(self, title: str, text: str,
             items: list[tuple[str, str]]) -> str | None:
        if self.kind == "kdialog":
            args = ["kdialog", "--title", title, "--menu", text]
            for tag, label in items:
                args += [tag, label]
            rc, out = self._run(args)
            return out if rc == 0 else None
        if self.kind == "zenity":
            args = ["zenity", "--list", "--title", title, "--text", text,
                    "--column", "Tag", "--column", "Option",
                    "--hide-column", "1", "--print-column", "1"]
            for tag, label in items:
                args += [tag, label]
            rc, out = self._run(args)
            return out if rc == 0 and out else None
        print(f"\n{title}: {text}")
        for tag, label in items:
            print(f"  {tag}) {label}")
        return input("Choice: ").strip() or None


# ---------------------------------------------------------------------------
# Steam / game discovery
# ---------------------------------------------------------------------------
def steam_roots() -> list[Path]:
    candidates = [
        Path.home() / ".local/share/Steam",
        Path.home() / ".steam/steam",
        Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam",
    ]
    out, seen = [], set()
    for c in candidates:
        if c.is_dir():
            real = c.resolve()
            if real not in seen:
                seen.add(real)
                out.append(c)
    return out


def library_paths(steam_root: Path) -> list[Path]:
    """Parse libraryfolders.vdf for all Steam library roots (incl. microSD)."""
    vdf = steam_root / "steamapps/libraryfolders.vdf"
    paths = [steam_root]
    if vdf.is_file():
        for m in re.finditer(r'"path"\s*"([^"]+)"',
                             vdf.read_text(errors="ignore")):
            paths.append(Path(m.group(1)))
    seen, out = set(), []
    for p in paths:
        if str(p) not in seen:
            seen.add(str(p))
            out.append(p)
    return out


def find_games() -> dict[str, tuple[Path, Path]]:
    """Return {game_key: (game_dir, steam_root)} for whatever is installed."""
    found: dict[str, tuple[Path, Path]] = {}
    for root in steam_roots():
        for lib in library_paths(root):
            for key, g in GAMES.items():
                if key in found:
                    continue
                d = lib / "steamapps/common" / g["dirname"]
                if (d / g["exe"]).is_file():
                    found[key] = (d, root)
    return found


# ---------------------------------------------------------------------------
# Download / extract helpers
# ---------------------------------------------------------------------------
def download(url: str, dest: Path, log, sha256: str | None = None) -> None:
    """Stream `url` to `dest`, verifying its SHA-256 if one is pinned.

    The hash is computed on the fly (no second read), and a mismatch deletes
    the partial file and aborts — a corrupted or tampered archive never
    reaches the extractor. Passing sha256=None (user-supplied Nexus archives,
    whose bytes we can't know ahead of time) skips only the hash check; the
    non-empty and content checks still apply.
    """
    log(f"  ↓ {url.rsplit('/', 1)[-1]}")
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    h = hashlib.sha256()
    with urllib.request.urlopen(req, timeout=300) as r, open(dest, "wb") as f:
        while True:
            chunk = r.read(1024 * 256)
            if not chunk:
                break
            h.update(chunk)
            f.write(chunk)
    if dest.stat().st_size == 0:
        dest.unlink(missing_ok=True)
        raise RuntimeError(f"Downloaded 0 bytes from {url}")
    if sha256 is not None:
        got = h.hexdigest()
        if got.lower() != sha256.lower():
            dest.unlink(missing_ok=True)
            raise RuntimeError(
                "Checksum mismatch — refusing to install a file that doesn't "
                f"match its pinned hash.\n\n  {url.rsplit('/', 1)[-1]}\n"
                f"  expected {sha256}\n  got      {got}\n\n"
                "The download was corrupted or the release was changed. "
                "Nothing was written to your game folder.")
        log(f"    ✓ sha256 verified")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 256), b""):
            h.update(chunk)
    return h.hexdigest()


def fetch(url: str, dest: Path, log, sha256: str | None = None) -> None:
    """Download `url` unless `dest` already holds the pinned bytes.

    Lets main() pre-download every archive a game needs BEFORE any destructive
    extraction, so a network failure strikes before — never after — large stock
    files are overwritten (those over BACKUP_MAX_BYTES can't be rolled back).
    The per-step install functions then reuse the cached, verified file.
    """
    if (dest.is_file() and sha256
            and sha256_file(dest).lower() == sha256.lower()):
        log(f"  ↓ (verified, already downloaded) {url.rsplit('/', 1)[-1]}")
        return
    download(url, dest, log, sha256=sha256)


# ---------------------------------------------------------------------------
# Safe extraction — validate an archive's paths BEFORE trusting its contents.
#
# bsdtar already refuses absolute paths and `..` members, but we don't rely on
# that: we extract to an isolated staging dir, then walk the result and reject
# anything unsafe (symlinks, hardlinks, or paths that escape staging) rather
# than copying a single malicious entry into the live game folder.
# ---------------------------------------------------------------------------
class UnsafeArchiveError(RuntimeError):
    pass


def _rel_is_unsafe(rel: str) -> bool:
    if not rel or rel.startswith("/") or rel.startswith("\\"):
        return True
    parts = re.split(r"[\\/]+", rel)
    return any(p in ("..",) for p in parts)


def staged_files(archive: Path, staging: Path) -> list[str]:
    """Extract `archive` into `staging` and return the safe relative paths.

    Raises UnsafeArchiveError if the archive lists an absolute/`..` path, or if
    anything extracted is a symlink or otherwise not a plain file/dir. The
    caller moves the returned paths into place; nothing here touches the game.
    """
    # 1. Pre-flight the listing — reject obviously hostile members up front.
    listing = subprocess.run(["bsdtar", "-tf", str(archive)],
                             capture_output=True, text=True, check=True)
    for ln in listing.stdout.splitlines():
        name = ln.rstrip("\r")
        if not name:
            continue
        if _rel_is_unsafe(name.rstrip("/")):
            raise UnsafeArchiveError(
                f"Archive '{archive.name}' contains an unsafe path "
                f"({name!r}); refusing to extract it.")

    # 2. Extract into the isolated staging dir.
    staging.mkdir(parents=True, exist_ok=True)
    subprocess.run(["bsdtar", "-xf", str(archive), "-C", str(staging)],
                   check=True)

    # 3. Walk what landed. Any symlink (dir or file) is a traversal risk once
    #    we copy through it, so reject the archive outright. os.walk does not
    #    follow symlinks, so a symlinked dir is seen here, not descended into.
    root = staging.resolve()
    files: list[str] = []
    for dirpath, dirnames, filenames in os.walk(staging):
        for d in dirnames:
            if os.path.islink(os.path.join(dirpath, d)):
                raise UnsafeArchiveError(
                    f"Archive '{archive.name}' contains a symlinked directory "
                    f"({d!r}); refusing to install it.")
        for fn in filenames:
            full = os.path.join(dirpath, fn)
            if os.path.islink(full):
                raise UnsafeArchiveError(
                    f"Archive '{archive.name}' contains a symlink "
                    f"({fn!r}); refusing to install it.")
            if not os.path.isfile(full):
                # sockets, fifos, devices — nothing a mod archive should hold.
                raise UnsafeArchiveError(
                    f"Archive '{archive.name}' contains a non-regular file "
                    f"({fn!r}); refusing to install it.")
            resolved = Path(full).resolve()
            if root not in resolved.parents and resolved != root:
                raise UnsafeArchiveError(
                    f"Archive '{archive.name}' path escapes staging "
                    f"({fn!r}); refusing to install it.")
            files.append(os.path.relpath(full, staging))
    return files


def free_gb(path: Path) -> float:
    st = os.statvfs(path)
    return st.f_bavail * st.f_frsize / (1024 ** 3)


def detect_device(env: dict | None = None,
                  dmi_bases: tuple[str, ...] | None = None) -> str:
    """Best-effort hardware profile: 'steam_deck' or 'generic_linux'.

    Only nudges menu defaults and the one genuine Deck-specific rule
    (Konami's high-res texture pack being unusable in-game there) — it can
    never block or change what gets installed. Not every SteamOS device is
    a Deck (Steam Machines, desktop SteamOS), so unknown hardware falls
    back to 'generic_linux'.
    """
    env = os.environ if env is None else env
    if env.get("SteamDeck"):
        return "steam_deck"
    for base in dmi_bases or ("/sys/class/dmi/id",
                              "/sys/devices/virtual/dmi/id"):
        try:
            vendor = (Path(base) / "sys_vendor").read_text().strip()
            product = (Path(base) / "product_name").read_text().strip()
        except OSError:
            continue
        # Jupiter = LCD Deck, Galileo = OLED Deck
        if vendor == "Valve" and product in ("Jupiter", "Galileo"):
            return "steam_deck"
    return "generic_linux"


# ---------------------------------------------------------------------------
# Transactional installer.
#
# Every file that lands in the game folder goes through one InstallTxn, which:
#   • stages + path-validates each archive before copying anything in,
#   • backs up any original it overwrites (small files only — see
#     BACKUP_MAX_BYTES),
#   • records every added/overwritten path plus the mod versions in a manifest,
#   • rolls the whole thing back if any step raises, and
#   • is replayed in reverse by uninstall_game().
#
# The manifest and backups live in <game>/mgs-modkit/, so repair and uninstall
# need nothing but the game folder itself.
# ---------------------------------------------------------------------------
class InstallTxn:
    def __init__(self, game_dir: Path, game_key: str, log) -> None:
        self.game_dir = game_dir
        self.game_key = game_key
        self.log = log
        self.root = game_dir / MODKIT_DIRNAME
        self.backups = self.root / "backups"
        self.staging = self.root / "staging"
        self.added: list[str] = []
        self.overwritten: list[dict] = []
        self.mods: dict[str, str] = {}
        self._added_set: set[str] = set()
        self._backed_up: set[str] = set()
        # Rollback bookkeeping, tracked separately from the uninstall manifest:
        # rollback must undo ONLY what THIS run did, and must never destroy a
        # previous install's recovery data (its manifest + backups).
        self._new_added: list[str] = []      # files this run created from scratch
        self._new_backups: list[str] = []    # backup rel-paths this run wrote
        # Whether a previous run of this kit is already installed here. Its
        # files are treated as "ours" (reclaimed, not re-backed-up as stock),
        # and on a failed re-install its manifest/backups are left intact.
        self._had_prior = False
        self._prior_added: set[str] = set()
        prev = self.root / MANIFEST_NAME
        if prev.is_file():
            try:
                data = json.loads(prev.read_text(encoding="utf-8"))
                self._prior_added = set(data.get("added", []))
                # Carry prior backups forward: the REAL stock originals are
                # already saved from the first run. On a re-install we must not
                # re-back-up our own mod files over them (that would lose the
                # true originals), and the manifest must keep pointing at them.
                for o in data.get("overwritten", []):
                    self.overwritten.append(o)
                    self._backed_up.add(o["path"])
                self._had_prior = True
            except (ValueError, OSError, KeyError):
                pass

    # -- recording -------------------------------------------------------
    def note_mod(self, name: str, version: str) -> None:
        self.mods[name] = version

    def _prepare_dest(self, rel: str) -> None:
        """Record what we're about to do to game_dir/rel (add vs overwrite)."""
        if rel in self._added_set:
            return  # already ours this run
        dest = self.game_dir / rel
        if dest.exists():
            if rel in self._prior_added:
                # Our own file from a previous run — reclaim it as added so
                # uninstall removes it, and don't back it up. It is NOT counted
                # as new-this-run: rollback must leave the previous install's
                # files in place, not delete them.
                self._added_set.add(rel)
                self.added.append(rel)
                return
            if rel not in self._backed_up:
                self._backed_up.add(rel)
                size = dest.stat().st_size
                if size <= BACKUP_MAX_BYTES:
                    bpath = self.backups / rel
                    bpath.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(dest, bpath)
                    self.overwritten.append(
                        {"path": rel, "backup": f"backups/{rel}"})
                    self._new_backups.append(rel)
                else:
                    self.overwritten.append({"path": rel, "backup": None})
        else:
            self._added_set.add(rel)
            self.added.append(rel)
            self._new_added.append(rel)

    # -- operations ------------------------------------------------------
    def install_archive(self, archive: Path) -> list[str]:
        """Stage-validate `archive`, then move its files into the game dir."""
        self.staging.mkdir(parents=True, exist_ok=True)
        stage = Path(tempfile.mkdtemp(prefix="stage_", dir=self.staging))
        try:
            rels = staged_files(archive, stage)
            for rel in rels:
                if _rel_is_unsafe(rel):
                    raise UnsafeArchiveError(
                        f"Refusing unsafe path {rel!r} from {archive.name}")
                self._prepare_dest(rel)
                dest = self.game_dir / rel
                dest.parent.mkdir(parents=True, exist_ok=True)
                src = stage / rel
                try:
                    os.replace(src, dest)          # fast path: same filesystem
                except OSError:
                    shutil.copy2(src, dest)        # cross-device fallback
            return rels
        finally:
            shutil.rmtree(stage, ignore_errors=True)

    def write_bytes(self, rel: str, data: bytes) -> None:
        """Create/replace a file we author (settings, launcher saves, ...)."""
        self._prepare_dest(rel)
        dest = self.game_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(data)

    def read_text_ours(self, rel: str, encoding: str = "utf-8") -> str:
        return (self.game_dir / rel).read_text(encoding=encoding)

    # -- finish ----------------------------------------------------------
    def commit(self) -> None:
        self.staging.mkdir(parents=True, exist_ok=True)
        shutil.rmtree(self.staging, ignore_errors=True)
        manifest = {
            "modkit_version": MODKIT_VERSION,
            "game": self.game_key,
            "installed_utc": datetime.now(timezone.utc)
                .replace(microsecond=0).isoformat(),
            "mods": self.mods,
            "added": self.added,
            "overwritten": self.overwritten,
        }
        self.root.mkdir(parents=True, exist_ok=True)
        (self.root / MANIFEST_NAME).write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8")

    def rollback(self) -> None:
        """Undo ONLY what this run did (best-effort, never raises).

        Files this run created are removed and stock originals this run backed
        up are restored. Files that belonged to a PREVIOUS install of this kit
        are left in place, and that previous install's manifest + backups are
        preserved — a failed re-install falls back to the last working install
        rather than orphaning files or destroying its recovery data.
        """
        # 1. Remove only files this run created from scratch.
        for rel in reversed(self._new_added):
            try:
                (self.game_dir / rel).unlink(missing_ok=True)
            except OSError:
                pass
        # 2. Restore stock originals this run overwrote-and-backed-up, then drop
        #    those now-irrelevant backup copies (they belong to this aborted run).
        for rel in self._new_backups:
            src = self.backups / rel
            if src.is_file():
                try:
                    dst = self.game_dir / rel
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(src, dst)
                    src.unlink(missing_ok=True)
                except OSError:
                    pass
        _prune_empty_dirs(self.game_dir, self._new_added)

        if self._had_prior:
            # Keep the previous install intact: leave its manifest.json (never
            # rewritten until commit) and its backups. Only clear this run's
            # transient staging.
            shutil.rmtree(self.staging, ignore_errors=True)
        else:
            # Fresh install that failed — nothing of ours should remain.
            shutil.rmtree(self.root, ignore_errors=True)


def _prune_empty_dirs(base: Path, rels: list[str]) -> None:
    """Remove now-empty directories left behind after files were removed."""
    seen: set[Path] = set()
    for rel in rels:
        d = (base / rel).parent
        while d != base and base in d.parents:
            seen.add(d)
            d = d.parent
    for d in sorted(seen, key=lambda p: len(str(p)), reverse=True):
        try:
            d.rmdir()
        except OSError:
            pass  # not empty (other files live here) — leave it


# ---------------------------------------------------------------------------
# Install steps  (ORDER MATTERS — see the mods' own README:
#   1. MGSHDFix  →  2. Better Audio  →  3. Bugfix Compilation Base)
# ---------------------------------------------------------------------------
def install_hdfix(tx: InstallTxn, tmp: Path, log) -> None:
    log(f"  Installing MGSHDFix {HDFIX_VERSION} …")
    zp = tmp / f"MGSHDFix_{HDFIX_VERSION}.zip"
    fetch(HDFIX_URL, zp, log, sha256=HDFIX_SHA256)
    tx.install_archive(zp)
    tx.note_mod("MGSHDFix", HDFIX_VERSION)
    missing = [n for n in ("winhttp.dll", "wininet.dll")
               if not (tx.game_dir / n).is_file()]
    if missing or not (tx.game_dir / "plugins" / "MGSHDFix.asi").is_file():
        raise RuntimeError(
            "MGSHDFix extraction failed (missing: "
            f"{', '.join(missing) or 'plugins/MGSHDFix.asi'})")
    log("    ✓ winhttp.dll + wininet.dll + plugins/MGSHDFix.asi")


def install_better_audio(tx: InstallTxn, archives: list[Path], log) -> None:
    for archive in archives:
        log(f"  Installing Better Audio Mod from {archive.name} "
            f"({archive.stat().st_size / 1024**3:.2f} GB) — this takes a while …")
        # install_archive stage-validates paths (no traversal/symlinks) and
        # moves every file into place, tracking it for rollback/uninstall.
        rels = tx.install_archive(archive)
        # Verify the payload actually landed — every file entry must exist.
        missing = [e for e in rels if not (tx.game_dir / e).is_file()]
        if missing:
            raise RuntimeError(
                f"Better Audio archive '{archive.name}': {len(missing)} "
                f"file(s) missing after extraction (e.g. {missing[0]}). "
                "The archive may be corrupt — re-download it and re-run "
                "this kit.")
        log(f"    ✓ {archive.name}: all {len(rels)} files verified on disk")
    tx.note_mod("Better Audio Mod", "+".join(a.name for a in archives))


def install_m2fix(tx: InstallTxn, tmp: Path, opts: dict, log) -> None:
    log(f"  Installing MGSM2Fix {M2FIX_VERSION} …")
    zp = tmp / f"MGSM2Fix_{M2FIX_VERSION}.zip"
    fetch(M2FIX_URL, zp, log, sha256=M2FIX_SHA256)
    tx.install_archive(zp)
    tx.note_mod("MGSM2Fix", M2FIX_VERSION)
    missing = [n for n in ("d3d11.dll", "dinput8.dll", "MGSM2Fix64.asi",
                           "MGSM2Fix.ini") if not (tx.game_dir / n).is_file()]
    if missing:
        raise RuntimeError(f"MGSM2Fix extraction failed (missing: "
                           f"{', '.join(missing)})")
    text = tx.read_text_ours("MGSM2Fix.ini")
    if not opts.get("update_check"):
        text = text.replace("CheckForUpdates = true",
                            "CheckForUpdates = false", 1)
    if opts.get("skip_launcher", True):
        # Safe even on a fresh install: per the author's docs this "boots
        # the LAST LAUNCHED game version", so until the user has picked a
        # version once, the selection menu still appears normally.
        text = text.replace("StartGame = false", "StartGame = true", 1)
    tx.write_bytes("MGSM2Fix.ini", text.encode("utf-8"))
    log("    ✓ d3d11.dll + dinput8.dll + MGSM2Fix (vanilla-faithful "
        "shipped defaults; auto-boots your last-picked version)")


def install_bugfix(tx: InstallTxn, g: dict, tmp: Path, log) -> None:
    log(f"  Installing {g['short']} Community Bugfix Compilation "
        f"{g['bugfix_version']} (Base) …")
    zp = tmp / f"{g['short']}_bugfix_base.zip"
    fetch(g["bugfix_url"], zp, log, sha256=g.get("bugfix_sha256"))
    tx.install_archive(zp)
    tx.note_mod(f"{g['short']} Community Bugfix Compilation",
                g["bugfix_version"])
    if not (tx.game_dir / "plugins" / g["bugfix_asi"]).is_file():
        raise RuntimeError(f"Bugfix Compilation failed (plugins/"
                           f"{g['bugfix_asi']} missing)")
    log(f"    ✓ plugins/{g['bugfix_asi']}")


def write_settings(tx: InstallTxn, g: dict, opts: dict, log) -> None:
    game_dir = tx.game_dir
    body = SETTINGS_TEMPLATE
    for ph, val in (
        ("@BUTTON_ICONS@", opts["button_icons"]),
        ("@REGION@", g["region"]),
        ("@SKIP_LAUNCHER@", "1" if opts["skip_launcher"] else "0"),
        ("@SKIP_SPLASH@", "1" if opts["skip_splash"] else "0"),
        ("@AUDIO_MODE@", opts["audio_mode"]),
        ("@UPDATE_CHECK@", "1" if opts["update_check"] else "0"),
    ):
        body = body.replace(ph, val)

    if "@" in re.sub(r"[^@]", "", body):  # any placeholder left unsubstituted
        raise RuntimeError("Internal error: unsubstituted settings placeholder")

    rel = "plugins/MGSHDFix.settings"
    # The Config Tool writes CRLF; match it exactly.
    tx.write_bytes(rel, body.replace("\n", "\r\n").encode("utf-8"))

    text = (game_dir / rel).read_text(encoding="utf-8")
    sections = len(re.findall(r"^\[", text, re.M))
    keys = len(re.findall(r"^[^\[\r\n][^\r\n]*=", text, re.M))
    if sections != SETTINGS_EXPECTED_SECTIONS or keys != SETTINGS_EXPECTED_KEYS:
        raise RuntimeError(
            f"Settings sanity check failed: got {sections} sections / {keys} "
            f"keys, expected {SETTINGS_EXPECTED_SECTIONS}/"
            f"{SETTINGS_EXPECTED_KEYS}")
    log(f"    ✓ plugins/MGSHDFix.settings ({sections} sections, {keys} keys)")


def steamid64s(steam_root: Path) -> list[int]:
    """Every Steam account on this machine, as steamid64."""
    out = []
    ud = steam_root / "userdata"
    if ud.is_dir():
        for d in ud.iterdir():
            if d.is_dir() and d.name.isdigit():
                out.append(int(d.name) + STEAMID64_BASE)
    return out


def _read_launcher_sv(path: Path) -> dict[str, str]:
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    return dict(zip(data["keyList"], data["valueList"]))


def _launcher_sv_bytes(keys: list[str], vals: list[str]) -> bytes:
    body = json.dumps({"keyList": keys, "valueList": vals},
                      separators=(",", ":"), ensure_ascii=False)
    # UTF-8 BOM + trailing CRLF, byte-for-byte as the launcher writes it.
    return b"\xef\xbb\xbf" + body.encode("utf-8") + b"\r\n"


def set_launcher_options(tx: InstallTxn, g: dict, steam_root: Path,
                         opts: dict, log) -> None:
    """Apply the launcher's own options so the launcher can be skipped.

    Writes go through the transaction, so an existing launcher_sv is backed
    up before we patch it (uninstall restores it) and a freshly synthesised
    one is tracked for removal.
    """
    game_dir = tx.game_dir
    wanted = {
        "HiresoMovie": "1" if opts["hq_movies"] else "0",
        # MGSHDFix owns resolution/upscaling; the launcher must stay at
        # Default/Original or the two fight each other.
        "HiresoRender": "0",
        "HiresoUpScale": "0",
    }
    if g["key"] == "mgs3" and opts.get("device", "steam_deck") == "steam_deck":
        # Deck only: Konami's official high-res texture pack installs on the
        # Steam Deck but cannot be used in-game there, so the flag is forced
        # off to keep the launcher from dead-ending. On other hardware an
        # existing HiresoTexture choice (e.g. the DLC genuinely in use on a
        # desktop) is preserved; fresh installs still default to 0 via the
        # template below.
        wanted["HiresoTexture"] = "0"

    save_root = game_dir / f"{g['dirname'].lower()}_savedata_win"
    existing = sorted(save_root.glob("*/launcher/launcher_sv"))

    if existing:
        for sv in existing:
            try:
                cur = _read_launcher_sv(sv)
            except (ValueError, KeyError, OSError) as e:
                log(f"    ⚠ couldn't parse {sv.name} ({e}); leaving it alone")
                continue
            cur.update(wanted)
            tx.write_bytes(str(sv.relative_to(game_dir)),
                           _launcher_sv_bytes(list(cur.keys()),
                                              list(cur.values())))
            log(f"    ✓ launcher options patched ({sv.parent.parent.name})")
        return

    # Fresh install — the launcher has never run, so synthesise its save.
    keys, vals = LAUNCHER_TEMPLATES[g["key"]]
    keys, vals = list(keys), list(vals)
    for k, v in wanted.items():
        if k in keys:
            vals[keys.index(k)] = v
        else:
            keys.append(k)
            vals.append(v)
    ids = steamid64s(steam_root)
    if not ids:
        log("    ⚠ no Steam account found; skipping launcher options "
            "(set them in the launcher on first run)")
        return
    for sid in ids:
        rel = f"{save_root.name}/{sid}/launcher/launcher_sv"
        tx.write_bytes(rel, _launcher_sv_bytes(keys, vals))
        log(f"    ✓ launcher options created ({sid})")


def verify_install(g: dict, game_dir: Path) -> list[str]:
    """Return a list of human-readable problems (empty == all good)."""
    if g.get("kind", "hdfix") == "m2fix":
        return [f"missing {rel}" for rel in
                ("d3d11.dll", "dinput8.dll", "MGSM2Fix64.asi", "MGSM2Fix.ini")
                if not (game_dir / rel).is_file()]
    problems = []
    for rel in ("winhttp.dll", "wininet.dll",
                "plugins/MGSHDFix.asi", "plugins/MGSHDFix.settings"):
        if not (game_dir / rel).is_file():
            problems.append(f"missing {rel}")
    if not (game_dir / "plugins" / g["bugfix_asi"]).is_file():
        problems.append(f"missing plugins/{g['bugfix_asi']}")
    return problems


# ---------------------------------------------------------------------------
# Uninstall — reverse a previous install using its manifest.
#
# Removes every file the kit added (newest-first so directories empty out),
# restores any original it backed up, and clears the obsolete legacy
# MGSM2Fix.asi that upstream warns can clash with the unified 3.x release.
# Multi-GB assets the Better Audio Mod overwrote were recorded but not backed
# up (see BACKUP_MAX_BYTES); Steam's "Verify integrity of game files" restores
# those, and we say so.
# ---------------------------------------------------------------------------
LEGACY_M2FIX_FILES = ("MGSM2Fix.asi",)


def uninstall_game(game_dir: Path, log) -> tuple[list[str], bool]:
    """Reverse a kit install in `game_dir`.

    Returns (notes, ok). If any file couldn't be removed or restored, ok is
    False AND the manifest + backups are LEFT IN PLACE — never delete the
    recovery data while a restore is still outstanding, and never report
    success when files are still in a half-reverted state. Re-running can then
    retry, or the user can restore by hand.
    """
    notes: list[str] = []
    errors = False
    root = game_dir / MODKIT_DIRNAME
    manifest = root / MANIFEST_NAME

    # Always clear the obsolete legacy unified .asi, manifest or not.
    for name in LEGACY_M2FIX_FILES:
        legacy = game_dir / name
        if legacy.is_file():
            try:
                legacy.unlink()
                notes.append(f"removed legacy {name}")
            except OSError as e:
                notes.append(f"couldn't remove legacy {name} ({e})")
                errors = True

    if not manifest.is_file():
        notes.append("no install manifest found — nothing tracked to remove "
                     "(use Steam → Verify integrity to reset any remaining "
                     "mod files)")
        return notes, not errors

    try:
        data = json.loads(manifest.read_text(encoding="utf-8"))
    except (ValueError, OSError) as e:
        notes.append(f"couldn't read manifest ({e}); left files in place")
        return notes, False

    added = data.get("added", [])
    overwritten = data.get("overwritten", [])

    # Restore originals FIRST (before removing added files), so a file that is
    # both added-by-us and has a stock backup ends up as the stock original.
    restored, verify_hint = 0, False
    for o in overwritten:
        rel, backup = o.get("path"), o.get("backup")
        if backup:
            src = root / backup
            if src.is_file():
                try:
                    dst = game_dir / rel
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(src, dst)
                    restored += 1
                except OSError as e:
                    notes.append(f"couldn't restore {rel} ({e})")
                    errors = True
            else:
                notes.append(f"backup for {rel} is missing; can't restore it")
                errors = True
        else:
            verify_hint = True

    removed = 0
    restored_paths = {o.get("path") for o in overwritten if o.get("backup")}
    for rel in reversed(added):
        if rel in restored_paths:
            continue  # a stock original was just put back here — keep it
        try:
            (game_dir / rel).unlink(missing_ok=True)
            removed += 1
        except OSError as e:
            notes.append(f"couldn't remove {rel} ({e})")
            errors = True
    if removed:
        notes.append(f"removed {removed} installed file(s)")
    if restored:
        notes.append(f"restored {restored} original file(s) from backup")
    if verify_hint:
        notes.append("some large originals (e.g. Better Audio assets) were "
                     "not backed up — run Steam → Verify integrity of game "
                     "files to restore them")

    _prune_empty_dirs(game_dir, added)
    if errors:
        notes.append("left the mgs-modkit backup/manifest folder in place so "
                     "you can retry — some files could not be reverted")
        return notes, False

    shutil.rmtree(root, ignore_errors=True)
    notes.append("removed the mgs-modkit backup/manifest folder")
    return notes, True


# ---------------------------------------------------------------------------
# Better Audio Mod: NexusMods requires a login, so we cannot fetch it.
# Try to find an already-downloaded archive, else let the user point at one.
# ---------------------------------------------------------------------------
MIN_AUDIO_BYTES = 500 * 1024 * 1024   # a Full Version is 2-3 GB
MIN_UPDATE_BYTES = 5 * 1024 * 1024    # small patch/update archives are fine


def scan_audio_archives(short: str) -> list[Path]:
    """All plausible Better Audio archives for this game, any size."""
    pats = [f"*{short}*Better*Audio*", f"*Better*Audio*{short}*",
            f"*{short}*BetterAudio*", f"*{short}MC*Audio*"]
    exts = {".zip", ".7z", ".rar"}
    roots = [Path.home() / "Downloads", Path.home() / "Desktop",
             Path.home() / "Documents", Path.home()]
    hits: set[Path] = set()
    for root in roots:
        if not root.is_dir():
            continue
        for pat in pats:
            for p in root.glob(pat):
                if (p.is_file() and p.suffix.lower() in exts
                        and p.stat().st_size >= MIN_UPDATE_BYTES):
                    hits.add(p)
    return sorted(hits, key=lambda p: p.stat().st_mtime)


def guess_audio_archive(short: str) -> Path | None:
    """Newest full-size Better Audio archive, or None."""
    full = [p for p in scan_audio_archives(short)
            if p.stat().st_size >= MIN_AUDIO_BYTES]
    return full[-1] if full else None


def audio_version(path: Path) -> tuple[int, int] | None:
    """Parse (major, minor) from a NexusMods download filename."""
    m = NEXUS_SUFFIX.search(path.name)
    return (int(m.group(2)), int(m.group(3))) if m else None


def audio_modid(path: Path) -> int | None:
    """Parse the NexusMods mod id from a download filename."""
    m = NEXUS_SUFFIX.search(path.name)
    return int(m.group(1)) if m else None


def scan_update_archives(short: str) -> list[Path]:
    """Small archives belonging to this game's Nexus mod page, by modid.

    Update files often have generic names ("Update 2.0-4-2-0-<ts>.zip"), so
    name-matching alone misses them — the modid in the suffix is authoritative.
    """
    modid = AUDIO_EXPECT.get(short, {}).get("modid")
    exts = {".zip", ".7z", ".rar"}
    roots = [Path.home() / "Downloads", Path.home() / "Desktop",
             Path.home() / "Documents", Path.home()]
    hits: set[Path] = set()
    for root in roots:
        if not root.is_dir():
            continue
        for p in root.iterdir():
            if (p.is_file() and p.suffix.lower() in exts
                    and MIN_UPDATE_BYTES <= p.stat().st_size < MIN_AUDIO_BYTES
                    and modid is not None and audio_modid(p) == modid):
                hits.add(p)
    hits.update(p for p in scan_audio_archives(short)
                if p.stat().st_size < MIN_AUDIO_BYTES)
    return sorted(hits, key=lambda p: (audio_version(p) or (0, 0),
                                       p.stat().st_mtime))


def probe_audio_archive(path: Path) -> bool:
    """Cheap sanity check that this really is an MGS audio mod archive."""
    p = subprocess.run(["bsdtar", "-tf", str(path)],
                       capture_output=True, text=True)
    if p.returncode != 0:
        return False
    names = p.stdout.lower()
    return ("us/" in names or ".sdt" in names or ".sdx" in names
            or ".xxs" in names)


def open_url(url: str) -> bool:
    if not shutil.which("xdg-open"):
        return False
    try:
        subprocess.Popen(["xdg-open", url],
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
    except OSError:
        return False


def obtain_audio_archives(g: dict, ui: UI) -> list[Path]:
    """Locate the Better Audio archive(s), walking the user through it.

    NexusMods requires a logged-in account to download, and the mod author
    does not permit the files being mirrored elsewhere — so this kit will
    never host or fetch them directly. We make the manual step as painless
    as possible instead: open the page, then pick the download up
    automatically from wherever the browser put it.
    """
    short = g["short"]
    arc = guess_audio_archive(short)
    if arc is None:
        if ui.yesno(
            f"No {short} Better Audio archive found on this machine.\n\n"
            "It's hosted on NexusMods, which needs a (free) login, and the "
            "author doesn't allow it to be mirrored — so it can't be "
            "downloaded automatically.\n\n"
            f"Open the page now?\n{g['audio_page']}\n\n"
            f"(Grab the FULL VERSION. Choosing No skips {short} audio.)"
        ):
            if not open_url(g["audio_page"]):
                ui.info(f"Couldn't open a browser. Visit:\n{g['audio_page']}")
            ui.info(
                f"Download the {short} Better Audio Mod (Full Version),\n"
                "then click OK here.\n\n"
                "I'll pick it up from your Downloads folder automatically —\n"
                "no need to tell me where it is.")
            arc = guess_audio_archive(short)

    expect = AUDIO_EXPECT.get(short, {})

    # Freshness: warn (never block) if the MAIN archive is older than the
    # page's current main file. NOTE: MGS3's main file is v1.0 and that IS
    # current — its 2.x content ships as a separate small update archive.
    ver = audio_version(arc) if arc else None
    cur = expect.get("full")
    if arc and ver and cur and ver < cur:
        if ui.yesno(
            f"Heads up: this {short} archive is version {ver[0]}.{ver[1]}, "
            f"but at least {cur[0]}.{cur[1]} exists on NexusMods:\n\n"
            f"{arc.name}\n\n"
            f"Open the page to download the current version instead?\n"
            f"(No = install {ver[0]}.{ver[1]} anyway)"
        ):
            open_url(g["audio_page"])
            ui.info("Download the current Full Version, then click OK here.")
            arc = guess_audio_archive(short) or arc

    if not (arc and ui.yesno(f"Use this for {short}?\n\n{arc}\n"
                             f"({arc.stat().st_size / 1024**3:.2f} GB)")):
        sel = ui.pick_file(f"Select the {short} Better Audio archive "
                           f"(Cancel to skip {short})")
        if not sel:
            return []
        arc = Path(sel)

    if not probe_audio_archive(arc):
        if not ui.yesno(
            f"WARNING: {arc.name} doesn't look like an MGS audio mod "
            "archive (no us/ folder or .sdt/.sdx/.xxs files inside).\n\n"
            "Install it anyway?"
        ):
            return []

    # Updates / optional extras from the same mod page, matched by the modid
    # in the Nexus filename suffix (their names may not mention the game at
    # all, e.g. "Update 2.0-4-2-0-<ts>.zip"). Required-style updates are
    # auto-included; cutscene/ending extras are offered as a choice.
    # Ordered by version then mtime, so the base is patched oldest-first.
    chosen = [arc]
    have_update = False
    for extra in scan_update_archives(short):
        if extra == arc or not probe_audio_archive(extra):
            continue
        name = extra.name.lower()
        if "cutscene" in name or "ending" in name:
            if ui.yesno(
                f"Optional extra found for {short} (separate from the "
                f"required Update):\n\n{extra.name} "
                f"({extra.stat().st_size / 1048576:.0f} MB)\n\n"
                "Higher-bitrate audio for the game's final two cutscenes, "
                "from the same mod page. Its author notes a quirk: those "
                "two cutscenes will PAUSE at the end and need a button "
                "press (A/X) to continue.\n\n"
                "Recommended for a first playthrough: No.\n\nInstall it?"
            ):
                chosen.append(extra)
        else:
            chosen.append(extra)
            uv = audio_version(extra)
            if uv and expect.get("update") and uv >= expect["update"]:
                have_update = True

    # MGS3's page splits the mod: main v1.0 archive + required "Update 2.0".
    if expect.get("update") and not have_update:
        u = expect["update"]
        if ui.yesno(
            f"The {short} Better Audio Mod also needs its small "
            f"'Update {u[0]}.{u[1]}' archive (~25 MB), which wasn't found "
            "on this machine.\n\n"
            f"Open the page to download it now?\n{g['audio_page']}\n\n"
            "(No = install without it; you can re-run this kit later)"
        ):
            open_url(g["audio_page"])
            ui.info("Download the Update archive (Files tab), then click "
                    "OK here.")
            for extra in scan_update_archives(short):
                if (extra not in chosen and probe_audio_archive(extra)
                        and not ("cutscene" in extra.name.lower()
                                 or "ending" in extra.name.lower())):
                    chosen.append(extra)
    return chosen


# ---------------------------------------------------------------------------
# Double-click shortcut self-cleanup
# ---------------------------------------------------------------------------
def normalize_desktop_path(raw: str | None) -> Path | None:
    if not raw:
        return None
    from urllib.parse import unquote, urlparse
    p = unquote(urlparse(raw).path) if raw.startswith("file://") else raw
    return Path(p)


def offer_self_cleanup(ui: UI, desktop: Path | None) -> None:
    if not desktop:
        return
    if ui.yesno("Delete this installer shortcut now?\n"
                "You won't need it again."):
        try:
            if desktop.is_file():
                desktop.unlink()
            Path("/tmp/mgs_install.py").unlink(missing_ok=True)
            ui.info("Installer shortcut deleted. Enjoy!")
        except OSError as e:
            ui.error(f"Couldn't delete the shortcut automatically:\n"
                     f"{desktop}\n\n{e}")


# ---------------------------------------------------------------------------
# Uninstall flow
# ---------------------------------------------------------------------------
def run_uninstall(ui: UI, log) -> int:
    found = find_games()
    if not found:
        manual = ui.pick_dir("Select the MGS game folder to un-mod")
        if not manual:
            ui.error("No install selected. Aborting.")
            return 1
        d = Path(manual)
        for key, g in GAMES.items():
            if (d / g["exe"]).is_file():
                found[key] = (d, Path.home())
        if not found:
            ui.error(f"No Master Collection game executable found in:\n{d}")
            return 1

    # Only offer games this kit actually touched (they have a manifest or the
    # legacy .asi worth clearing).
    modded = {k: v for k, v in found.items()
              if (v[0] / MODKIT_DIRNAME / MANIFEST_NAME).is_file()
              or any((v[0] / n).is_file() for n in LEGACY_M2FIX_FILES)}
    if not modded:
        ui.info("Nothing to uninstall — none of the detected games has a "
                "mgs-modkit manifest from this installer.")
        return 0

    if len(modded) > 1:
        picks = ui.checklist(
            "MGS Mod Kit — Uninstall",
            "Remove this kit's mods from:",
            [(k, f"{GAMES[k]['name']}  ({modded[k][0]})", True)
             for k in modded],
        )
        if not picks:
            ui.error("Nothing selected. Aborting.")
            return 1
        modded = {k: v for k, v in modded.items() if k in picks}

    names = ", ".join(GAMES[k]["short"] for k in modded)
    if not ui.yesno(
        f"Uninstall this kit's mods from {names}?\n\n"
        "Files this kit added will be removed and any originals it backed up "
        "restored. Your game saves are untouched.\n\n"
        "Make sure THE GAMES AND STEAM'S DOWNLOADS ARE CLOSED. Proceed?"
    ):
        return 0

    all_ok = True
    for key in modded:
        g, (game_dir, _) = GAMES[key], modded[key]
        log(f"\n=== Uninstalling {g['name']} ===")
        notes, ok = uninstall_game(game_dir, log)
        all_ok = all_ok and ok
        for note in notes:
            log(f"    • {note}")

    if not all_ok:
        ui.error(
            f"{names}: uninstall finished with problems — some files could "
            "not be removed or restored, so the mgs-modkit backup/manifest "
            "folder was kept for a retry.\n\n"
            "Close the games and Steam's downloads, then run --uninstall "
            "again, or use Steam → Properties → Installed Files → Verify "
            "integrity of game files to reset to stock.")
        return 1

    ui.info(
        f"✅ {names} un-modded.\n\n"
        "Remove the leftover Steam Launch Options too: right-click each game "
        "in Steam → Properties → General → Launch Options and clear the "
        "WINEDLLOVERRIDES line.\n\n"
        "MGSHDFix also writes a logs/ folder and steam_appid.txt at runtime; "
        "delete those if you want a spotless folder, or just run Steam → "
        "Verify integrity of game files.")
    return 0


# ---------------------------------------------------------------------------
# Main flow
# ---------------------------------------------------------------------------
def main() -> int:
    ui = UI()
    logs: list[str] = []

    import argparse
    ap = argparse.ArgumentParser(add_help=False)
    ap.add_argument("--desktop", default=None,
                    help="Path of the launching .desktop shortcut (internal).")
    ap.add_argument("--uninstall", action="store_true",
                    help="Reverse a previous install (restore backups, remove "
                         "added files) instead of installing.")
    cli, _ = ap.parse_known_args()
    desktop = normalize_desktop_path(cli.desktop)

    def log(msg: str) -> None:
        print(msg)
        logs.append(msg)

    if cli.uninstall:
        return run_uninstall(ui, log)

    if not shutil.which("bsdtar"):
        ui.error("`bsdtar` is required but not found. On SteamOS it is "
                 "preinstalled; otherwise install libarchive/bsdtar and re-run.")
        return 1

    # 1. Find the games -----------------------------------------------------
    found = find_games()
    if not found:
        ui.info("Couldn't auto-detect any Master Collection game "
                "(MGS1, MGS2 or MGS3).\n\n"
                "Next you'll be asked to point at a game folder manually "
                "(the one containing 'METAL GEAR SOLID.exe', "
                "'METAL GEAR SOLID2.exe' or 'METAL GEAR SOLID3.exe').")
        manual = ui.pick_dir("Select your MGS1, MGS2 or MGS3 folder")
        if not manual:
            ui.error("No install selected. Aborting.")
            return 1
        d = Path(manual)
        for key, g in GAMES.items():
            if (d / g["exe"]).is_file():
                found[key] = (d, next(iter(steam_roots()),
                                      Path.home() / ".local/share/Steam"))
        if not found:
            ui.error("No Master Collection game executable (METAL GEAR "
                     "SOLID.exe / SOLID2.exe / SOLID3.exe) was found in:\n"
                     f"{d}")
            return 1

    # 2. Which games to process --------------------------------------------
    if len(found) > 1:
        picks = ui.checklist(
            "MGS Mod Kit — Choose Games",
            f"{len(found)} Master Collection games detected. "
            "Install mods for:",
            [(k, f"{GAMES[k]['name']}  ({found[k][0]})", True) for k in found],
        )
        if not picks:
            ui.error("No games selected. Aborting.")
            return 1
        found = {k: v for k, v in found.items() if k in picks}

    # 3. Options -----------------------------------------------------------
    # skip_launcher / update_check apply to BOTH the MGSHDFix games and MGS1
    # (MGSM2Fix), so they're offered whenever any game is selected — an
    # MGS1-only install must not silently inherit the defaults with no say.
    hdfix_sel = [k for k in found if GAMES[k].get("kind", "hdfix") == "hdfix"]
    m2fix_sel = [k for k in found if GAMES[k].get("kind") == "m2fix"]
    device = detect_device()
    opts = {
        "device": device,
        "button_icons": "Steam Deck", "audio_mode": "Stereo (2.0)",
        "hq_movies": True, "skip_splash": True,
        "update_check": False, "skip_launcher": True,
    }
    if hdfix_sel:
        # Detection only reorders the menu so the likeliest choice is
        # preselected — every option stays available on every device.
        icon_items = [
            ("Steam Deck", "Steam Deck — matches the Deck's physical buttons"),
            ("Xbox One", "Xbox — Steam Machine / Xbox-style pads"),
            ("PlayStation 5", "PlayStation 5 — for a DualSense"),
            ("PlayStation 2", "PlayStation 2 — authentic, restored by the Bugfix mod"),
            ("Keyboard / Mouse", "Keyboard / Mouse"),
        ]
        if device != "steam_deck":
            icon_items.insert(0, icon_items.pop(1))    # Xbox first
        opts["button_icons"] = ui.menu(
            "Controller Button Icons",
            "Which button prompts should MGS2/MGS3 show?",
            icon_items,
        ) or icon_items[0][0]

        opts["audio_mode"] = ui.menu(
            "Audio Output",
            "How are you listening?",
            [("Stereo (2.0)", "Stereo — handheld, headphones, TV speakers "
                              "(right for most setups, incl. docked)"),
             ("Surround Sound (5.1)", "5.1 Surround — ONLY with a real "
                                      "surround receiver / speaker setup")],
        ) or "Stereo (2.0)"

    # Build the extras checklist from whatever's actually selected.
    # (No MGS3 high-res texture option: Konami's official texture pack can be
    # installed on the Steam Deck but cannot be used in-game, so the kit
    # always leaves HiresoTexture=0.)
    extra_items: list[tuple[str, str, bool]] = []
    if hdfix_sel:
        extra_items += [
            ("hq_movies", "High-quality cinematics  (set for you — no "
                          "launcher trip needed)", True),
            ("skip_splash", "Skip the unskippable KONAMI intro logos", True),
        ]
    if hdfix_sel or m2fix_sel:
        skip_label = ("Boot straight into the games ("
                      + " / ".join(filter(None, [
                          "skip MGS2/3's Konami launcher" if hdfix_sel else "",
                          "MGS1 re-boots your last-picked version"
                          if m2fix_sel else ""])) + ")")
        extra_items += [
            ("skip_launcher", skip_label, True),
            ("update_check", "Check for mod updates on launch", False),
        ]
    if extra_items:
        extras = ui.checklist(
            "Extra Options", "Optional tweaks (recommended defaults shown):",
            extra_items,
        )
        # None == the user cancelled the dialog: keep the recommended
        # defaults rather than reading a cancel as "turn everything off".
        if extras is not None:
            for tag, _, _ in extra_items:
                opts[tag] = tag in extras

    # 4. Better Audio Mod (manual archive, MGS2/MGS3 only) -------------------
    audio_archives: dict[str, list[Path]] = {}
    if hdfix_sel and ui.yesno(
        "Install the Better Audio Mod? (STRONGLY recommended)\n\n"
        "It restores the higher-quality audio the port shipped re-compressed "
        "(ported from the PS3 HD Collection) — cutscenes and codec calls.\n"
        "For MGS2 it also replaces a corrupted audio file that can freeze "
        "or crash a late-game cutscene.\n\n"
        "About 2-3 GB per game. If it's already downloaded I'll find it; "
        "otherwise I'll open the download page for you.\n\n"
        "Install it? (No = skip; you can re-run this kit any time)"
    ):
        for key in hdfix_sel:
            arcs = obtain_audio_archives(GAMES[key], ui)
            if arcs:
                audio_archives[key] = arcs

    # 5. Confirm ------------------------------------------------------------
    plan = []
    for key in found:
        g, (d, _) = GAMES[key], found[key]
        if g.get("kind", "hdfix") == "m2fix":
            bits = [f"MGSM2Fix {M2FIX_VERSION} (vanilla defaults)"]
        else:
            bits = [f"MGSHDFix {HDFIX_VERSION}"]
            if key in audio_archives:
                bits.append("Better Audio Mod ["
                            + " + ".join(a.name for a in audio_archives[key])
                            + "]")
            bits.append(f"Bugfix Compilation {g['bugfix_version']} (Base)")
            bits.append("tuned MGSHDFix.settings")
        plan.append(f"• {g['short']}  →  {d}\n    {' + '.join(bits)}")

    target_dir = next(iter(found.values()))[0]
    summary = (
        f"Device: {'Steam Deck (detected)' if device == 'steam_deck' else 'Linux / SteamOS PC'}"
        f"    Free space: {free_gb(target_dir):.0f} GB\n\n")
    if hdfix_sel:
        summary = (
            f"Button icons: {opts['button_icons']}    "
            f"Audio: {opts['audio_mode']}\n"
            f"Skip logos: {'yes' if opts['skip_splash'] else 'no'}    "
            f"Skip launcher: {'yes' if opts['skip_launcher'] else 'no'}\n\n"
            + summary)
    if not ui.yesno(
        "Ready to install:\n\n" + "\n".join(plan) + "\n\n" + summary +
        "Make sure THE GAMES AND STEAM'S DOWNLOADS ARE CLOSED. Proceed?"
    ):
        return 0

    # 6. Do the work --------------------------------------------------------
    # Each game is installed in its own transaction: on any failure that game
    # is rolled back to exactly how it was found (added files removed, backed-up
    # originals restored), so no half-modified install is left behind. Games
    # already committed before the failure stay installed.
    try:
        with tempfile.TemporaryDirectory(prefix="mgskit_") as td:
            tmp = Path(td)
            for key in found:
                g, (game_dir, sroot) = GAMES[key], found[key]
                log(f"\n=== {g['name']} ===")
                tx = InstallTxn(game_dir, key, log)
                try:
                    if g.get("kind", "hdfix") == "m2fix":
                        install_m2fix(tx, tmp, opts, log)
                    else:
                        # Pre-download every networked archive BEFORE touching
                        # the game, so a download failure can't strike after the
                        # large, un-backed-up Better Audio files are overwritten.
                        log("  Downloading mods (verifying checksums) …")
                        fetch(HDFIX_URL, tmp / f"MGSHDFix_{HDFIX_VERSION}.zip",
                              log, sha256=HDFIX_SHA256)
                        fetch(g["bugfix_url"],
                              tmp / f"{g['short']}_bugfix_base.zip",
                              log, sha256=g.get("bugfix_sha256"))
                        install_hdfix(tx, tmp, log)              # 1
                        if key in audio_archives:                # 2
                            install_better_audio(tx, audio_archives[key], log)
                        install_bugfix(tx, g, tmp, log)          # 3
                        write_settings(tx, g, opts, log)
                        set_launcher_options(tx, g, sroot, opts, log)
                    tx.commit()
                except BaseException:
                    log(f"  ✗ {g['short']} failed — rolling back its changes …")
                    tx.rollback()
                    raise
                for f in tmp.glob("*.zip"):
                    f.unlink(missing_ok=True)
    except (urllib.error.URLError, urllib.error.HTTPError, RuntimeError,
            subprocess.CalledProcessError, OSError) as e:
        ui.error(f"Install failed:\n\n{e}\n\n"
                 "The affected game was rolled back — files this run added were "
                 "removed and the fix-mod originals it backed up restored (a "
                 "failed re-install falls back to your previous working setup). "
                 "The large Better Audio stock files aren't backed up, so if "
                 "audio had already been written, run Steam → Properties → "
                 "Installed Files → Verify integrity to be safe. You can also "
                 "re-run this kit, or --uninstall.")
        return 1

    # 7. Verify -------------------------------------------------------------
    all_problems = []
    for key in found:
        probs = verify_install(GAMES[key], found[key][0])
        if probs:
            all_problems.append(f"{GAMES[key]['short']}: {', '.join(probs)}")
    if all_problems:
        ui.error("Install finished but verification found problems:\n\n"
                 + "\n".join(all_problems))
        return 1

    # 8. Final manual steps -------------------------------------------------
    names = ", ".join(GAMES[k]["short"] for k in found)
    lo_lines = []
    if hdfix_sel:
        lo_lines.append("   "
                        + " & ".join(GAMES[k]["short"] for k in hdfix_sel)
                        + f":  {LAUNCH_OPTIONS}")
    for key in found:
        if GAMES[key].get("kind") == "m2fix":
            lo_lines.append(f"   {GAMES[key]['short']}:  "
                            f"{GAMES[key]['launch']}")
    launcher_note = ""
    if hdfix_sel:
        launcher_note = (
            "3) The Konami launcher is SKIPPED — MGS2/MGS3 boot straight "
            "in.\n"
            f"   High-quality cinematics: "
            f"{'ON' if opts['hq_movies'] else 'off'} (already applied).\n"
            "   Need the launcher back? Edit plugins/MGSHDFix.settings →\n"
            "   Skip Launcher=0\n\n"
            if opts["skip_launcher"] else
            "3) The Konami launcher will still appear on launch. Its "
            "options\n"
            f"   are already set for you (high-quality cinematics: "
            f"{'ON' if opts['hq_movies'] else 'off'}), so just hit Play.\n"
            "   To skip it entirely, edit plugins/MGSHDFix.settings →\n"
            "   Skip Launcher=1\n\n"
        )
    ui.info(
        f"✅ Done — {names} modded and verified!\n\n"
        "ONE manual step remains (Steam reverts script-made edits, so this\n"
        "must be done in Steam's UI):\n\n"
        "1) LAUNCH OPTIONS — for EACH game, right-click it in Steam →\n"
        "   Properties → General → Launch Options, and paste EXACTLY\n"
        "   (note they differ per game):\n\n"
        + "\n".join(lo_lines) + "\n\n"
        "   Without this, the fix mods will not load at all.\n\n"
        "2) Playing docked / on a TV? SteamOS may default the game to\n"
        "   1280x720 — set Properties → General → Game Resolution to\n"
        "   'Native' (or 1920x1080) for full quality. Handheld needs no\n"
        "   changes; everything renders at native 16:10.\n\n"
        + launcher_note +
        ("4) MGS1 FIRST BOOT — the version-select menu appears once. Pick\n"
         "   METAL GEAR SOLID (US) — full-speed 60Hz English; the EU disc\n"
         "   is 50Hz PAL and runs ~17% slower. In the display options pick\n"
         "   Max resolution and keep 4:3. After that it boots straight in\n"
         "   (change versions later via the in-game pause menu).\n\n"
         if any(GAMES[k].get("kind") == "m2fix" for k in found) else "")
        +
        "If MGS2/MGS3 ever report a missing config key, run\n"
        "'MGSHDFix Config Tool.exe' in the game's plugins folder and hit\n"
        "'Save and Exit' — that regenerates the settings file.\n\n"
        "You Enjoy All Weapons And Equipment From The Start Of The Game!"
    )
    offer_self_cleanup(ui, desktop)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\nAborted.")
        sys.exit(130)
