#!/usr/bin/env python3
"""
Metal Gear Solid 2 & 3 (Master Collection) — Steam Deck Mod Kit
===============================================================
A guided, dependency-free installer for the "essential" vanilla-faithful mod
stack on the Steam Deck (and any Linux Steam install).

It will:
  1. Auto-detect your MGS2 / MGS3 Master Collection installs (incl. microSD).
  2. Install MGSHDFix (resolution / 16:10 / FOV / CPU fixes) — REQUIRED.
  3. Install the Community Bugfix Compilation (Base) — restores the original
     PS2 textures/models and fixes the port's broken assets.
  4. Optionally install the Better Audio Mod from a zip you supply (it lives on
     NexusMods, which requires a login, so it cannot be fetched automatically).
  5. Write a KNOWN-GOOD MGSHDFix.settings file, tuned for the Deck.
  6. Set the Konami launcher's own options for you — including "high quality
     cinematics" — so the launcher can be skipped entirely.

Steps 5 and 6 are the whole reason this kit exists. MGSHDFix has no runtime defaults:
without a complete settings file it refuses to boot, and it hard-aborts on any
single missing section or key. That file can only be produced by its Windows
Config Tool, and its ini section names are NOT the names shown in that tool's
UI, so hand-writing one does not work. This kit ships a canonical file captured
from the real Config Tool, so you never have to run it under Proton.

Mods are downloaded live from their official GitHub releases — nothing is
rehosted here.

It deliberately does NOT set Steam launch options: Steam rewrites its config
from memory and will silently revert edits made while it is running. The one
line you must paste is shown at the end.

Requirements (all preinstalled on SteamOS): python3, bsdtar, and kdialog OR
zenity. No pip packages, no sudo.

Run it from the Desktop (Konsole):  python3 install.py
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.error
import urllib.request
from pathlib import Path

UA = "Mozilla/5.0 (X11; Linux x86_64) mgs-mc-deck-modkit"

# ---------------------------------------------------------------------------
# Pinned versions.
#
# These three versions are pinned ON PURPOSE. The bundled MGSHDFix.settings
# below was generated by MGSHDFix 3.1.0's own Config Tool, and a future
# MGSHDFix release may rename ini sections/keys — which would make the game
# hard-abort on launch. Pinning guarantees a tested, working combination.
# To move to a newer MGSHDFix, bump HDFIX_VERSION and regenerate the settings
# file with the Config Tool (see README).
# ---------------------------------------------------------------------------
HDFIX_VERSION = "3.1.0"
HDFIX_URL = (
    "https://github.com/ShizCalev/MGSHDFix/releases/download/"
    f"{HDFIX_VERSION}/MGSHDFix_{HDFIX_VERSION}.zip"
)

GAMES = {
    "mgs2": {
        "key": "mgs2",
        "name": "Metal Gear Solid 2: Sons of Liberty",
        "short": "MGS2",
        "appid": "2131640",
        "dirname": "MGS2",
        "exe": "METAL GEAR SOLID2.exe",
        # Region value the Config Tool writes for this title's option list.
        "region": "eu",
        "bugfix_version": "2.2.0",
        "bugfix_url": (
            "https://github.com/ShizCalev/MGS2-Community-Bugfix-Compilation/"
            "releases/download/2.2.0/"
            "MGS2-Community-Bugfix-Compilation_Base_v2.2.0.zip"
        ),
        "bugfix_asi": "MGS2-Community-Bugfix-Compilation.asi",
        "audio_page": "https://www.nexusmods.com/metalgearsolid2mc/mods/3",
    },
    "mgs3": {
        "key": "mgs3",
        "name": "Metal Gear Solid 3: Snake Eater",
        "short": "MGS3",
        "appid": "2131650",
        "dirname": "MGS3",
        "exe": "METAL GEAR SOLID3.exe",
        "region": "us",
        "bugfix_version": "1.1.0",
        "bugfix_url": (
            "https://github.com/ShizCalev/MGS3-Community-Bugfix-Compilation/"
            "releases/download/1.1.0/"
            "MGS3-Community-Bugfix-Compilation_Base_v1.1.0.zip"
        ),
        "bugfix_asi": "MGS3-Community-Bugfix-Compilation.asi",
        "audio_page": "https://www.nexusmods.com/metalgearsolid3mc/mods/4",
    },
}

LAUNCH_OPTIONS = 'WINEDLLOVERRIDES="wininet,winhttp=n,b" %command%'

# ---------------------------------------------------------------------------
# Canonical MGSHDFix.settings (MGSHDFix 3.1.0).
#
# Captured verbatim from the real "MGSHDFix Config Tool.exe" — 150 lines,
# 96 keys, 27 sections. Placeholders (@NAME@) are substituted at write time.
# Written with CRLF line endings, exactly as the Config Tool writes it.
#
# Note the section names: [Internal Settings], [Launcher Config],
# [Skip Logo Screens], [MGS2 - Model Options] ... these are NOT the tab labels
# shown in the Config Tool's UI. Getting these wrong makes the game refuse to
# start with "Failed to read config key 'X' in section 'Y': Section not found".
# ---------------------------------------------------------------------------
SETTINGS_TEMPLATE = """\
[Bugfixes]
Fix  High  CPU  Usage="Full"
Fix Achievement Stat Tracking=1
Fix Aiming After Equip=1
Fix Aiming On Full Tilt=1
Fix Alt-Tab Loading Bugs=1
Fix Effect Speeds=1
Fix Mouse Cursor Showing=1
Fix Rain Width=1
Fix UI Width=1
Line Scale Size=360
MGS2 - Fix Optical Camo Refraction=1

[CAUTION - THIS WILL RESET ALL ACHIEVEMENTS]
Reset All Achievements=0
Safety Switch=0

[Camera Positioning]
Disable HD Collection Camera Positioning=0
HD Collection Camera Toggle="F6"

[Caption Settings]
Caption Opacity (%)=100
Caption Outline Opacity (%)=100
Caption Size (%)=100

[Controller Settings]
Button Icons="@BUTTON_ICONS@"
Set Menu OK && Cancel Button="Default"

[DISABLE STEAM ACHIEVEMENTS]
Disable Unlocking Steam Achievements=0

[Damaged Steam Cloud Save Data Fix]
Enable Console Notification When Fixed=1
Fix Mode="Move Outdated Save Data to Backup Folder"

[Enable Game Warnings]
Warn When FSR Upscaling is Enabled=1
Warn When Game is Muted=1
Warn When Missing Major Bugfix Mods=1
Warn When Save Files Are Read-Only=1
Warn When Save Folders Not Writable=1
Warn When Windows Slideshow Enabled=1

[Hotkeys]
Capture Hotkeys While Alt-Tabbed=0
Cycle Wireframe Mode="End"
Toggle Always Show Grass="Page Up"
Toggle Rain Shader="Insert"
Toggle UI Shader="Delete"

[Internal Resolution / Render Scale (+ Downsampling / Supersampling / 21:9+ and 4:3 Support)]
Render Height=0
Render Width=0

[Internal Settings]
Debug Logging=0

[Keep Aiming After Firing]
Always Keep Aiming=0
MGS2 - While in FPS Mode=0
While Holding Lock On=1
While in First Person=1

[Language Settings]
Game Language="en"
Game Region="@REGION@"

[Launcher Config]
MSX Skip Launcher Game="Metal Gear (MSX)"
Skip Launcher=@SKIP_LAUNCHER@

[MGS2 - Difficulty Restoration]
Enable Grenade Cooking=0
Restore PS2 Solidus Choking Difficulty="Disabled"
Toggle Grenade Cooking="Num9"

[MGS2 - First Person Shooter Mode]
Enable First Person Shooter Mode=0
First Person Shooter - Movement Enabled By Default=1
Tap to Keep First Person View Active=0
Toggle First Person Shooter Mode="Right"
Toggle First Person Shooter Movement="Down"
Toggle Tap for First Person View="Up"

[MGS2 - Model Options]
Force High Quality Hostages=1
Force High Quality Marines=1
Force High Quality Player Models=1
Force RTC Hostage Type="Normal"

[MGS2 - Third Person Freecam]
Camera - Zoom In Hotkey="WheelUp"
Camera - Zoom Out Hotkey="WheelDown"
Camera - Zoom Reset Hotkey="Mouse4"
Camera - Zoom Speed=25
Camera - Zoom Step Amount=250
Enable Third Person Freecam=0
Horizontal Camera Sensitivity=0.600000
Inherit Camera Rotation=0
Inherit Camera Rotation Toggle="NumMultiply"
Max Camera Distance=4000
Third Person View Toggle="Mouse5"
Vertical Camera Sensitivity=0.400000

[MGS3 - Override Render Distance]
Always Show Grass=1
Custom Grass Distance Multiplier=1.000000

[Mouse Sensitivity]
Override Mouse Sensitivity=0
X Multiplier=1
Y Multiplier=1

[Skip Logo Screens]
Skip In-Game Splashscreens=@SKIP_SPLASH@
Skip Launcher Splashscreens=@SKIP_SPLASH@

[System Specific Fixes]
Audio Output Mode="@AUDIO_MODE@"
Disable Windows Fullscreen Optimization=0
Limit Game to 2 CPU Cores=0

[Texture Filtering]
Anisotropic Filtering Level=16
Nearest Neighbor Texture Filtering=0

[Ultra-Wide / 16:10+]
Fix Aspect Ratio=1
Fix FOV=1
Fix Framebuffer=1
Lock HUD && Movies to 16:9=0

[Update Notifications]
Check For MGSHDFix Updates=@UPDATE_CHECK@
In-Game Update Notifications=1

[Various]
MGS2 - Force Sunglasses="Normal"
MGS2 - Restore Japanese Phone Ringtone=1
MGS2 - Restore Original Dogtag Names=1
Pause On Focus Loss=0

[Window Settings]
Enable Resolution Overrides=1
Fullscreen, Borderless, and Windowed="Borderless Fullscreen"
Window Height=0
Window Width=0

"""

SETTINGS_EXPECTED_SECTIONS = 27
SETTINGS_EXPECTED_KEYS = 96

# ---------------------------------------------------------------------------
# The Konami launcher's own settings.
#
# The launcher persists its options to
#   <game>/<name>_savedata_win/<steamid64>/launcher/launcher_sv
# which is plain JSON with a UTF-8 BOM, stored as two parallel arrays:
#   {"keyList":["HiresoMovie",...],"valueList":["1",...]}
#
# The keys we care about:
#   HiresoMovie    1 = "high quality" cinematics  (the one everyone wants)
#   HiresoRender   internal resolution   -> 0, MGSHDFix owns resolution
#   HiresoUpScale  internal upscaling    -> 0, ditto
#   HiresoTexture  high-res textures (MGS3 only)
#
# Writing this ourselves is what lets the kit skip the launcher entirely:
# otherwise the launcher is the ONLY place those options can be set.
#
# Templates below are used only when no save exists yet (a fresh install).
# When one already exists we patch it in place and leave everything else —
# volume, language, MGS2's big ScenarioSave blob — untouched.
# ---------------------------------------------------------------------------
LAUNCHER_TEMPLATES = {
    "mgs2": (
        ["GDPRHash", "firstStart", "languageLauncher", "HiresoPreset",
         "launcherMasterVolume", "launcherMute", "HiresoRender",
         "HiresoUpScale", "HiresoMovie", "prevPlayLanguage",
         "prevPlayLanguage2", "prevGameRegion", "prevSelectStartUpNumber"],
        ["first", "0", "1", "2", "10", "0", "0", "0", "1", "2", "0", "2", "-1"],
    ),
    "mgs3": (
        ["GDPRHash", "firstStart", "languageLauncher", "HiresoPreset",
         "HiresoRender", "HiresoUpScale", "HiresoMovie", "HiresoTexture",
         "launcherMasterVolume", "launcherMute", "prevPlayLanguage",
         "prevPlayLanguage2", "prevGameRegion", "prevSelectStartUpNumber"],
        ["first", "0", "1", "2", "0", "0", "1", "0", "10", "0", "2", "0",
         "1", "-1"],
    ),
}

STEAMID64_BASE = 76561197960265728


# ---------------------------------------------------------------------------
# Tiny GUI abstraction: prefer kdialog (KDE/Deck desktop), fall back to zenity,
# then to a plain-terminal prompt so the script still works headless.
# ---------------------------------------------------------------------------
class UI:
    def __init__(self) -> None:
        self.kind = (
            "kdialog" if shutil.which("kdialog")
            else "zenity" if shutil.which("zenity")
            else "term"
        )

    def _run(self, args: list[str]) -> tuple[int, str]:
        p = subprocess.run(args, capture_output=True, text=True)
        return p.returncode, p.stdout.strip()

    def info(self, text: str, title: str = "MGS Deck Mod Kit") -> None:
        if self.kind == "kdialog":
            self._run(["kdialog", "--title", title, "--msgbox", text])
        elif self.kind == "zenity":
            self._run(["zenity", "--info", "--title", title,
                       "--no-wrap", "--text", text])
        else:
            print(f"\n=== {title} ===\n{text}\n")

    def error(self, text: str, title: str = "MGS Deck Mod Kit — Error") -> None:
        if self.kind == "kdialog":
            self._run(["kdialog", "--title", title, "--error", text])
        elif self.kind == "zenity":
            self._run(["zenity", "--error", "--title", title,
                       "--no-wrap", "--text", text])
        else:
            print(f"\n!!! {title} !!!\n{text}\n", file=sys.stderr)

    def yesno(self, text: str, title: str = "MGS Deck Mod Kit") -> bool:
        if self.kind == "kdialog":
            return self._run(["kdialog", "--title", title, "--yesno", text])[0] == 0
        if self.kind == "zenity":
            return self._run(["zenity", "--question", "--title", title,
                              "--no-wrap", "--text", text])[0] == 0
        return input(f"{text} [y/N] ").strip().lower().startswith("y")

    def pick_dir(self, text: str) -> str | None:
        start = str(Path.home())
        if self.kind == "kdialog":
            rc, out = self._run(["kdialog", "--title", text,
                                 "--getexistingdirectory", start])
            return out or None if rc == 0 else None
        if self.kind == "zenity":
            rc, out = self._run(["zenity", "--file-selection", "--directory",
                                 "--title", text])
            return out or None if rc == 0 else None
        ans = input(f"{text}\nPath: ").strip()
        return ans or None

    def pick_file(self, text: str, start: Path | None = None) -> str | None:
        start_s = str(start or (Path.home() / "Downloads"))
        if self.kind == "kdialog":
            rc, out = self._run(["kdialog", "--title", text,
                                 "--getopenfilename", start_s, "*.zip *.7z *.rar"])
            return out or None if rc == 0 else None
        if self.kind == "zenity":
            rc, out = self._run(["zenity", "--file-selection", "--title", text,
                                 "--filename", start_s + "/"])
            return out or None if rc == 0 else None
        ans = input(f"{text}\nPath to archive (blank to skip): ").strip()
        return ans or None

    def checklist(self, title: str, text: str,
                  items: list[tuple[str, str, bool]]) -> list[str]:
        """items: (tag, label, checked). Returns selected tags."""
        if self.kind == "kdialog":
            args = ["kdialog", "--title", title, "--separate-output",
                    "--checklist", text]
            for tag, label, chk in items:
                args += [tag, label, "on" if chk else "off"]
            rc, out = self._run(args)
            return out.splitlines() if rc == 0 else []
        if self.kind == "zenity":
            args = ["zenity", "--list", "--checklist", "--title", title,
                    "--text", text,
                    "--column", "Pick", "--column", "Tag", "--column", "Item",
                    "--hide-column", "2", "--print-column", "2"]
            for tag, label, chk in items:
                args += ["TRUE" if chk else "FALSE", tag, label]
            rc, out = self._run(args)
            return out.split("|") if rc == 0 and out else []
        print(f"\n{title}\n{text}")
        for i, (tag, label, chk) in enumerate(items):
            print(f"  [{i}] {'x' if chk else ' '} {label}")
        raw = input("Enter numbers to toggle (space-separated, blank=keep defaults): ")
        chosen = {tag for tag, _, chk in items if chk}
        if raw.strip():
            toggles = {int(x) for x in raw.split() if x.isdigit()}
            chosen = set()
            for i, (tag, _, chk) in enumerate(items):
                if chk ^ (i in toggles):
                    chosen.add(tag)
        return list(chosen)

    def menu(self, title: str, text: str,
             items: list[tuple[str, str]]) -> str | None:
        if self.kind == "kdialog":
            args = ["kdialog", "--title", title, "--menu", text]
            for tag, label in items:
                args += [tag, label]
            rc, out = self._run(args)
            return out if rc == 0 else None
        if self.kind == "zenity":
            args = ["zenity", "--list", "--title", title, "--text", text,
                    "--column", "Tag", "--column", "Option",
                    "--hide-column", "1", "--print-column", "1"]
            for tag, label in items:
                args += [tag, label]
            rc, out = self._run(args)
            return out if rc == 0 and out else None
        print(f"\n{title}: {text}")
        for tag, label in items:
            print(f"  {tag}) {label}")
        return input("Choice: ").strip() or None


# ---------------------------------------------------------------------------
# Steam / game discovery
# ---------------------------------------------------------------------------
def steam_roots() -> list[Path]:
    candidates = [
        Path.home() / ".local/share/Steam",
        Path.home() / ".steam/steam",
        Path.home() / ".var/app/com.valvesoftware.Steam/.local/share/Steam",
    ]
    out, seen = [], set()
    for c in candidates:
        if c.is_dir():
            real = c.resolve()
            if real not in seen:
                seen.add(real)
                out.append(c)
    return out


def library_paths(steam_root: Path) -> list[Path]:
    """Parse libraryfolders.vdf for all Steam library roots (incl. microSD)."""
    vdf = steam_root / "steamapps/libraryfolders.vdf"
    paths = [steam_root]
    if vdf.is_file():
        for m in re.finditer(r'"path"\s*"([^"]+)"',
                             vdf.read_text(errors="ignore")):
            paths.append(Path(m.group(1)))
    seen, out = set(), []
    for p in paths:
        if str(p) not in seen:
            seen.add(str(p))
            out.append(p)
    return out


def find_games() -> dict[str, tuple[Path, Path]]:
    """Return {game_key: (game_dir, steam_root)} for whatever is installed."""
    found: dict[str, tuple[Path, Path]] = {}
    for root in steam_roots():
        for lib in library_paths(root):
            for key, g in GAMES.items():
                if key in found:
                    continue
                d = lib / "steamapps/common" / g["dirname"]
                if (d / g["exe"]).is_file():
                    found[key] = (d, root)
    return found


# ---------------------------------------------------------------------------
# Download / extract helpers
# ---------------------------------------------------------------------------
def download(url: str, dest: Path, log) -> None:
    log(f"  ↓ {url.rsplit('/', 1)[-1]}")
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=300) as r, open(dest, "wb") as f:
        shutil.copyfileobj(r, f)
    if dest.stat().st_size == 0:
        raise RuntimeError(f"Downloaded 0 bytes from {url}")


def extract(archive: Path, dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    subprocess.run(["bsdtar", "-xf", str(archive), "-C", str(dest)], check=True)


def free_gb(path: Path) -> float:
    st = os.statvfs(path)
    return st.f_bavail * st.f_frsize / (1024 ** 3)


# ---------------------------------------------------------------------------
# Install steps  (ORDER MATTERS — see the mods' own README:
#   1. MGSHDFix  →  2. Better Audio  →  3. Bugfix Compilation Base)
# ---------------------------------------------------------------------------
def install_hdfix(game_dir: Path, tmp: Path, log) -> None:
    log(f"  Installing MGSHDFix {HDFIX_VERSION} …")
    zp = tmp / f"MGSHDFix_{HDFIX_VERSION}.zip"
    download(HDFIX_URL, zp, log)
    extract(zp, game_dir)
    missing = [n for n in ("winhttp.dll", "wininet.dll")
               if not (game_dir / n).is_file()]
    if missing or not (game_dir / "plugins" / "MGSHDFix.asi").is_file():
        raise RuntimeError(
            "MGSHDFix extraction failed (missing: "
            f"{', '.join(missing) or 'plugins/MGSHDFix.asi'})")
    log("    ✓ winhttp.dll + wininet.dll + plugins/MGSHDFix.asi")


def install_better_audio(game_dir: Path, archive: Path, log) -> None:
    log(f"  Installing Better Audio Mod from {archive.name} "
        f"({archive.stat().st_size / 1024**3:.2f} GB) — this takes a while …")
    extract(archive, game_dir)
    log("    ✓ audio streams replaced")


def install_bugfix(g: dict, game_dir: Path, tmp: Path, log) -> None:
    log(f"  Installing {g['short']} Community Bugfix Compilation "
        f"{g['bugfix_version']} (Base) …")
    zp = tmp / f"{g['short']}_bugfix_base.zip"
    download(g["bugfix_url"], zp, log)
    extract(zp, game_dir)
    if not (game_dir / "plugins" / g["bugfix_asi"]).is_file():
        raise RuntimeError(f"Bugfix Compilation failed (plugins/"
                           f"{g['bugfix_asi']} missing)")
    log(f"    ✓ plugins/{g['bugfix_asi']}")


def write_settings(game_dir: Path, g: dict, opts: dict, log) -> None:
    body = SETTINGS_TEMPLATE
    for ph, val in (
        ("@BUTTON_ICONS@", opts["button_icons"]),
        ("@REGION@", g["region"]),
        ("@SKIP_LAUNCHER@", "1" if opts["skip_launcher"] else "0"),
        ("@SKIP_SPLASH@", "1" if opts["skip_splash"] else "0"),
        ("@AUDIO_MODE@", opts["audio_mode"]),
        ("@UPDATE_CHECK@", "1" if opts["update_check"] else "0"),
    ):
        body = body.replace(ph, val)

    if "@" in re.sub(r"[^@]", "", body):  # any placeholder left unsubstituted
        raise RuntimeError("Internal error: unsubstituted settings placeholder")

    plugins = game_dir / "plugins"
    plugins.mkdir(exist_ok=True)
    dest = plugins / "MGSHDFix.settings"
    # The Config Tool writes CRLF; match it exactly.
    dest.write_bytes(body.replace("\n", "\r\n").encode("utf-8"))

    text = dest.read_text(encoding="utf-8")
    sections = len(re.findall(r"^\[", text, re.M))
    keys = len(re.findall(r"^[^\[\r\n][^\r\n]*=", text, re.M))
    if sections != SETTINGS_EXPECTED_SECTIONS or keys != SETTINGS_EXPECTED_KEYS:
        raise RuntimeError(
            f"Settings sanity check failed: got {sections} sections / {keys} "
            f"keys, expected {SETTINGS_EXPECTED_SECTIONS}/"
            f"{SETTINGS_EXPECTED_KEYS}")
    log(f"    ✓ plugins/MGSHDFix.settings ({sections} sections, {keys} keys)")


def steamid64s(steam_root: Path) -> list[int]:
    """Every Steam account on this machine, as steamid64."""
    out = []
    ud = steam_root / "userdata"
    if ud.is_dir():
        for d in ud.iterdir():
            if d.is_dir() and d.name.isdigit():
                out.append(int(d.name) + STEAMID64_BASE)
    return out


def _read_launcher_sv(path: Path) -> dict[str, str]:
    import json
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    return dict(zip(data["keyList"], data["valueList"]))


def _write_launcher_sv(path: Path, keys: list[str], vals: list[str]) -> None:
    import json
    body = json.dumps({"keyList": keys, "valueList": vals},
                      separators=(",", ":"), ensure_ascii=False)
    path.parent.mkdir(parents=True, exist_ok=True)
    # UTF-8 BOM + trailing CRLF, byte-for-byte as the launcher writes it.
    path.write_bytes(b"\xef\xbb\xbf" + body.encode("utf-8") + b"\r\n")


def set_launcher_options(game_dir: Path, g: dict, steam_root: Path,
                         opts: dict, log) -> None:
    """Apply the launcher's own options so the launcher can be skipped."""
    wanted = {
        "HiresoMovie": "1" if opts["hq_movies"] else "0",
        # MGSHDFix owns resolution/upscaling; the launcher must stay at
        # Default/Original or the two fight each other.
        "HiresoRender": "0",
        "HiresoUpScale": "0",
    }
    if g["key"] == "mgs3":
        wanted["HiresoTexture"] = "1" if opts.get("hq_textures") else "0"

    save_root = game_dir / f"{g['dirname'].lower()}_savedata_win"
    existing = sorted(save_root.glob("*/launcher/launcher_sv"))

    if existing:
        for sv in existing:
            try:
                cur = _read_launcher_sv(sv)
            except (ValueError, KeyError, OSError) as e:
                log(f"    ⚠ couldn't parse {sv.name} ({e}); leaving it alone")
                continue
            cur.update(wanted)
            _write_launcher_sv(sv, list(cur.keys()), list(cur.values()))
            log(f"    ✓ launcher options patched ({sv.parent.parent.name})")
        return

    # Fresh install — the launcher has never run, so synthesise its save.
    keys, vals = LAUNCHER_TEMPLATES[g["key"]]
    keys, vals = list(keys), list(vals)
    for k, v in wanted.items():
        if k in keys:
            vals[keys.index(k)] = v
        else:
            keys.append(k)
            vals.append(v)
    ids = steamid64s(steam_root)
    if not ids:
        log("    ⚠ no Steam account found; skipping launcher options "
            "(set them in the launcher on first run)")
        return
    for sid in ids:
        _write_launcher_sv(save_root / str(sid) / "launcher" / "launcher_sv",
                           keys, vals)
        log(f"    ✓ launcher options created ({sid})")


def verify_install(g: dict, game_dir: Path) -> list[str]:
    """Return a list of human-readable problems (empty == all good)."""
    problems = []
    for rel in ("winhttp.dll", "wininet.dll",
                "plugins/MGSHDFix.asi", "plugins/MGSHDFix.settings"):
        if not (game_dir / rel).is_file():
            problems.append(f"missing {rel}")
    if not (game_dir / "plugins" / g["bugfix_asi"]).is_file():
        problems.append(f"missing plugins/{g['bugfix_asi']}")
    return problems


# ---------------------------------------------------------------------------
# Better Audio Mod: NexusMods requires a login, so we cannot fetch it.
# Try to find an already-downloaded archive, else let the user point at one.
# ---------------------------------------------------------------------------
MIN_AUDIO_BYTES = 500 * 1024 * 1024  # the real mods are 2-3 GB; ignore stubs


def guess_audio_archive(short: str) -> Path | None:
    """Find an already-downloaded Better Audio archive, newest first."""
    pats = [f"*{short}*Better*Audio*", f"*Better*Audio*{short}*",
            f"*{short}*BetterAudio*", f"*{short}MC*Audio*"]
    exts = {".zip", ".7z", ".rar"}
    roots = [Path.home() / "Downloads", Path.home() / "Desktop",
             Path.home() / "Documents", Path.home()]
    hits: list[Path] = []
    for root in roots:
        if not root.is_dir():
            continue
        for pat in pats:
            for p in root.glob(pat):
                if (p.is_file() and p.suffix.lower() in exts
                        and p.stat().st_size >= MIN_AUDIO_BYTES):
                    hits.append(p)
    if not hits:
        return None
    # newest wins — most likely the one just downloaded
    return max(set(hits), key=lambda p: p.stat().st_mtime)


def open_url(url: str) -> bool:
    if not shutil.which("xdg-open"):
        return False
    try:
        subprocess.Popen(["xdg-open", url],
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        return True
    except OSError:
        return False


def obtain_audio_archive(g: dict, ui: UI) -> Path | None:
    """Locate the Better Audio archive, walking the user through it if needed.

    NexusMods requires a logged-in account to download, and the mod author
    does not permit the files being mirrored elsewhere — so this kit will
    never host or fetch them directly. We make the manual step as painless
    as possible instead: open the page, then pick the download up
    automatically from wherever the browser put it.
    """
    arc = guess_audio_archive(g["short"])
    if arc is None:
        if ui.yesno(
            f"No {g['short']} Better Audio archive found on this machine.\n\n"
            "It's hosted on NexusMods, which needs a (free) login, and the "
            "author doesn't allow it to be mirrored — so it can't be "
            "downloaded automatically.\n\n"
            f"Open the page now?\n{g['audio_page']}\n\n"
            f"(Grab the FULL VERSION. Choosing No skips {g['short']} audio.)"
        ):
            if not open_url(g["audio_page"]):
                ui.info(f"Couldn't open a browser. Visit:\n{g['audio_page']}")
            ui.info(
                f"Download the {g['short']} Better Audio Mod (Full Version),\n"
                "then click OK here.\n\n"
                "I'll pick it up from your Downloads folder automatically —\n"
                "no need to tell me where it is.")
            arc = guess_audio_archive(g["short"])

    if arc and ui.yesno(f"Use this for {g['short']}?\n\n{arc}\n"
                        f"({arc.stat().st_size / 1024**3:.2f} GB)"):
        return arc

    sel = ui.pick_file(f"Select the {g['short']} Better Audio archive "
                       f"(Cancel to skip {g['short']})")
    return Path(sel) if sel else None


# ---------------------------------------------------------------------------
# Double-click shortcut self-cleanup
# ---------------------------------------------------------------------------
def normalize_desktop_path(raw: str | None) -> Path | None:
    if not raw:
        return None
    from urllib.parse import unquote, urlparse
    p = unquote(urlparse(raw).path) if raw.startswith("file://") else raw
    return Path(p)


def offer_self_cleanup(ui: UI, desktop: Path | None) -> None:
    if not desktop:
        return
    if ui.yesno("Delete this installer shortcut now?\n"
                "You won't need it again."):
        try:
            if desktop.is_file():
                desktop.unlink()
            Path("/tmp/mgs_install.py").unlink(missing_ok=True)
            ui.info("Installer shortcut deleted. Enjoy!")
        except OSError as e:
            ui.error(f"Couldn't delete the shortcut automatically:\n"
                     f"{desktop}\n\n{e}")


# ---------------------------------------------------------------------------
# Main flow
# ---------------------------------------------------------------------------
def main() -> int:
    ui = UI()
    logs: list[str] = []

    import argparse
    ap = argparse.ArgumentParser(add_help=False)
    ap.add_argument("--desktop", default=None,
                    help="Path of the launching .desktop shortcut (internal).")
    cli, _ = ap.parse_known_args()
    desktop = normalize_desktop_path(cli.desktop)

    def log(msg: str) -> None:
        print(msg)
        logs.append(msg)

    if not shutil.which("bsdtar"):
        ui.error("`bsdtar` is required but not found. On SteamOS it is "
                 "preinstalled; otherwise install libarchive/bsdtar and re-run.")
        return 1

    # 1. Find the games -----------------------------------------------------
    found = find_games()
    if not found:
        ui.info("Couldn't auto-detect MGS2 or MGS3.\n\n"
                "Next you'll be asked to point at a game folder manually "
                "(the one containing 'METAL GEAR SOLID2.exe' or "
                "'METAL GEAR SOLID3.exe').")
        manual = ui.pick_dir("Select your MGS2 or MGS3 folder")
        if not manual:
            ui.error("No install selected. Aborting.")
            return 1
        d = Path(manual)
        for key, g in GAMES.items():
            if (d / g["exe"]).is_file():
                found[key] = (d, next(iter(steam_roots()),
                                      Path.home() / ".local/share/Steam"))
        if not found:
            ui.error(f"Neither game executable was found in:\n{d}")
            return 1

    # 2. Which games to process --------------------------------------------
    if len(found) > 1:
        picks = ui.checklist(
            "MGS Mod Kit — Choose Games",
            "Both games detected. Install mods for:",
            [(k, f"{GAMES[k]['name']}  ({found[k][0]})", True) for k in found],
        )
        if not picks:
            ui.error("No games selected. Aborting.")
            return 1
        found = {k: v for k, v in found.items() if k in picks}

    # 3. Options ------------------------------------------------------------
    icons = ui.menu(
        "Controller Button Icons",
        "Which button prompts should the games show?",
        [("Steam Deck", "Steam Deck — matches the Deck's physical buttons"),
         ("Xbox One", "Xbox — for an Xbox-style pad"),
         ("PlayStation 5", "PlayStation 5 — for a DualSense"),
         ("PlayStation 2", "PlayStation 2 — authentic, restored by the Bugfix mod"),
         ("Keyboard / Mouse", "Keyboard / Mouse")],
    ) or "Steam Deck"

    audio = ui.menu(
        "Audio Output",
        "How are you listening?",
        [("Stereo (2.0)", "Stereo — handheld speakers / headphones (Deck default)"),
         ("Surround Sound (5.1)", "5.1 Surround — docked to a receiver/TV")],
    ) or "Stereo (2.0)"

    extras = ui.checklist(
        "Extra Options", "Optional tweaks (recommended defaults shown):",
        [("hq_movies", "High-quality cinematics  (set for you — no launcher "
                       "trip needed)", True),
         ("skip_splash", "Skip the unskippable KONAMI intro logos", True),
         ("skip_launcher", "Skip the Konami launcher and boot straight into "
                           "the game", True),
         ("hq_textures", "MGS3 only: high-resolution textures", False),
         ("update_check", "Check for MGSHDFix updates on launch", False)],
    )
    opts = {
        "button_icons": icons,
        "audio_mode": audio,
        "hq_movies": "hq_movies" in extras,
        "hq_textures": "hq_textures" in extras,
        "skip_splash": "skip_splash" in extras,
        "update_check": "update_check" in extras,
        "skip_launcher": "skip_launcher" in extras,
    }

    # 4. Better Audio Mod (manual archive) ----------------------------------
    audio_archives: dict[str, Path] = {}
    if ui.yesno(
        "Install the Better Audio Mod?\n\n"
        "It restores the higher-quality audio the port shipped re-compressed "
        "(ported from the PS3 HD Collection) — cutscenes and codec calls.\n\n"
        "About 2-3 GB per game. If it's already downloaded I'll find it; "
        "otherwise I'll open the download page for you.\n\n"
        "Install it? (No = skip; you can re-run this kit any time)"
    ):
        for key in found:
            arc = obtain_audio_archive(GAMES[key], ui)
            if arc:
                audio_archives[key] = arc

    # 5. Confirm ------------------------------------------------------------
    plan = []
    for key in found:
        g, (d, _) = GAMES[key], found[key]
        bits = [f"MGSHDFix {HDFIX_VERSION}"]
        if key in audio_archives:
            bits.append("Better Audio Mod")
        bits.append(f"Bugfix Compilation {g['bugfix_version']} (Base)")
        bits.append("tuned MGSHDFix.settings")
        plan.append(f"• {g['short']}  →  {d}\n    {' + '.join(bits)}")

    target_dir = next(iter(found.values()))[0]
    if not ui.yesno(
        "Ready to install:\n\n" + "\n".join(plan) + "\n\n"
        f"Button icons: {icons}    Audio: {audio}\n"
        f"Skip logos: {'yes' if opts['skip_splash'] else 'no'}    "
        f"Skip launcher: {'yes' if opts['skip_launcher'] else 'no'}\n\n"
        f"Free space: {free_gb(target_dir):.0f} GB\n\n"
        "Make sure BOTH GAMES AND STEAM'S DOWNLOADS ARE CLOSED. Proceed?"
    ):
        return 0

    # 6. Do the work --------------------------------------------------------
    try:
        with tempfile.TemporaryDirectory(prefix="mgskit_") as td:
            tmp = Path(td)
            for key in found:
                g, (game_dir, sroot) = GAMES[key], found[key]
                log(f"\n=== {g['name']} ===")
                install_hdfix(game_dir, tmp, log)            # 1
                if key in audio_archives:                    # 2
                    install_better_audio(game_dir, audio_archives[key], log)
                install_bugfix(g, game_dir, tmp, log)        # 3
                write_settings(game_dir, g, opts, log)
                set_launcher_options(game_dir, g, sroot, opts, log)
                for f in tmp.glob("*.zip"):
                    f.unlink(missing_ok=True)
    except (urllib.error.URLError, urllib.error.HTTPError, RuntimeError,
            subprocess.CalledProcessError, OSError) as e:
        ui.error(f"Install failed:\n\n{e}\n\n"
                 "Your game files may be partially modified — re-run this kit, "
                 "or use Steam → Properties → Installed Files → Verify "
                 "integrity to reset to stock.")
        return 1

    # 7. Verify -------------------------------------------------------------
    all_problems = []
    for key in found:
        probs = verify_install(GAMES[key], found[key][0])
        if probs:
            all_problems.append(f"{GAMES[key]['short']}: {', '.join(probs)}")
    if all_problems:
        ui.error("Install finished but verification found problems:\n\n"
                 + "\n".join(all_problems))
        return 1

    # 8. Final manual steps -------------------------------------------------
    names = ", ".join(GAMES[k]["short"] for k in found)
    launcher_note = (
        "3) The Konami launcher is SKIPPED — the games boot straight in.\n"
        f"   High-quality cinematics: {'ON' if opts['hq_movies'] else 'off'} "
        "(already applied for you).\n"
        "   Need the launcher back? Edit plugins/MGSHDFix.settings →\n"
        "   Skip Launcher=0\n\n"
        if opts["skip_launcher"] else
        "3) The Konami launcher will still appear on launch. Its options\n"
        f"   are already set for you (high-quality cinematics: "
        f"{'ON' if opts['hq_movies'] else 'off'}), so you can just hit Play.\n"
        "   To skip it entirely, edit plugins/MGSHDFix.settings →\n"
        "   Skip Launcher=1\n\n"
    )
    ui.info(
        f"✅ Done — {names} modded and verified!\n\n"
        "ONE manual step remains (Steam reverts script-made edits, so this\n"
        "must be done in Steam's UI):\n\n"
        "1) LAUNCH OPTIONS — for EACH game, right-click it in Steam →\n"
        "   Properties → General → Launch Options, and paste EXACTLY:\n\n"
        f"   {LAUNCH_OPTIONS}\n\n"
        "   Without this, MGSHDFix will not load at all.\n\n"
        "2) Play in whatever mode you like — handheld Game Mode is fully\n"
        "   supported; the games render at your native 16:10 resolution.\n\n"
        + launcher_note +
        "If a game ever reports a missing config key, run\n"
        "'MGSHDFix Config Tool.exe' in the game's plugins folder and hit\n"
        "'Save and Exit' — that regenerates the settings file.\n\n"
        "You Enjoy All Weapons And Equipment From The Start Of The Game!"
    )
    offer_self_cleanup(ui, desktop)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\nAborted.")
        sys.exit(130)
